In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import json
from scipy.stats import trim_mean
import math
from pandas.api.types import ( is_numeric_dtype, is_categorical_dtype, is_object_dtype, is_datetime64_any_dtype )

In [2]:
df = pd.read_csv("../data/application_train.csv")
df.head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

In [3]:
def create_files_nulls_per_colmun(data_frame,table_name):
    nulls=data_frame.isna().sum()
    nulls.head()
    nulls.to_csv("dumps_from_notebooks/" + "null_count_" + table_name,index=True)
    porcentaje_of_nulls = (nulls * 100) / len(data_frame)
    porcentaje_of_nulls.head()
    porcentaje_of_nulls.to_csv("dumps_from_notebooks/null_porcentaje_" + table_name,index=False)

In [4]:
with open("../metadata/schema.json", "r") as f:
    schema = json.load(f)
print(schema)

{'application': {'SK_ID_CURR': {'type': 'categorical'}, 'TARGET': {'type': 'categorical'}, 'NAME_CONTRACT_TYPE': {'type': 'categorical'}, 'CODE_GENDER': {'type': 'categorical'}, 'FLAG_OWN_CAR': {'type': 'categorical'}, 'FLAG_OWN_REALTY': {'type': 'categorical'}, 'CNT_CHILDREN': {'type': 'numerical'}, 'AMT_INCOME_TOTAL': {'type': 'numerical'}, 'AMT_CREDIT': {'type': 'numerical'}, 'AMT_ANNUITY': {'type': 'numerical'}, 'AMT_GOODS_PRICE': {'type': 'numerical'}, 'NAME_TYPE_SUITE': {'type': 'categorical'}, 'NAME_INCOME_TYPE': {'type': 'categorical'}, 'NAME_EDUCATION_TYPE': {'type': 'categorical'}, 'NAME_FAMILY_STATUS': {'type': 'categorical'}, 'NAME_HOUSING_TYPE': {'type': 'categorical'}, 'REGION_POPULATION_RELATIVE': {'type': 'numerical'}, 'DAYS_BIRTH': {'type': 'numerical'}, 'DAYS_EMPLOYED': {'type': 'numerical'}, 'DAYS_REGISTRATION': {'type': 'numerical'}, 'DAYS_ID_PUBLISH': {'type': 'numerical'}, 'OWN_CAR_AGE': {'type': 'numerical'}, 'FLAG_MOBIL': {'type': 'categorical'}, 'FLAG_EMP_PHONE': {'type': 'categorical'}, 'FLAG_WORK_PHONE': {'type': 'categorical'}, 'FLAG_CONT_MOBILE': {'type': 'categorical'}, 'FLAG_PHONE': {'type': 'categorical'}, 'FLAG_EMAIL': {'type': 'categorical'}, 'OCCUPATION_TYPE': {'type': 'categorical'}, 'CNT_FAM_MEMBERS': {'type': 'numerical'}, 'REGION_RATING_CLIENT': {'type': 'categorical'}, 'REGION_RATING_CLIENT_W_CITY': {'type': 'categorical'}, 'WEEKDAY_APPR_PROCESS_START': {'type': 'categorical'}, 'HOUR_APPR_PROCESS_START': {'type': 'categorical'}, 'REG_REGION_NOT_LIVE_REGION': {'type': 'categorical'}, 'REG_REGION_NOT_WORK_REGION': {'type': 'categorical'}, 'LIVE_REGION_NOT_WORK_REGION': {'type': 'categorical'}, 'REG_CITY_NOT_LIVE_CITY': {'type': 'categorical'}, 'REG_CITY_NOT_WORK_CITY': {'type': 'categorical'}, 'LIVE_CITY_NOT_WORK_CITY': {'type': 'categorical'}, 'ORGANIZATION_TYPE': {'type': 'categorical'}, 'EXT_SOURCE_1': {'type': 'numerical'}, 'EXT_SOURCE_2': {'type': 'numerical'}, 'EXT_SOURCE_3': {'type': 'numerical'}, 'APARTMENTS_AVG': {'type': 'numerical'}, 'BASEMENTAREA_AVG': {'type': 'numerical'}, 'YEARS_BEGINEXPLUATATION_AVG': {'type': 'numerical'}, 'YEARS_BUILD_AVG': {'type': 'numerical'}, 'COMMONAREA_AVG': {'type': 'numerical'}, 'ELEVATORS_AVG': {'type': 'numerical'}, 'ENTRANCES_AVG': {'type': 'numerical'}, 'FLOORSMAX_AVG': {'type': 'numerical'}, 'FLOORSMIN_AVG': {'type': 'numerical'}, 'LANDAREA_AVG': {'type': 'numerical'}, 'LIVINGAPARTMENTS_AVG': {'type': 'numerical'}, 'LIVINGAREA_AVG': {'type': 'numerical'}, 'NONLIVINGAPARTMENTS_AVG': {'type': 'numerical'}, 'NONLIVINGAREA_AVG': {'type': 'numerical'}, 'APARTMENTS_MODE': {'type': 'numerical'}, 'BASEMENTAREA_MODE': {'type': 'numerical'}, 'YEARS_BEGINEXPLUATATION_MODE': {'type': 'numerical'}, 'YEARS_BUILD_MODE': {'type': 'numerical'}, 'COMMONAREA_MODE': {'type': 'numerical'}, 'ELEVATORS_MODE': {'type': 'numerical'}, 'ENTRANCES_MODE': {'type': 'numerical'}, 'FLOORSMAX_MODE': {'type': 'numerical'}, 'FLOORSMIN_MODE': {'type': 'numerical'}, 'LANDAREA_MODE': {'type': 'numerical'}, 'LIVINGAPARTMENTS_MODE': {'type': 'numerical'}, 'LIVINGAREA_MODE': {'type': 'numerical'}, 'NONLIVINGAPARTMENTS_MODE': {'type': 'numerical'}, 'NONLIVINGAREA_MODE': {'type': 'numerical'}, 'APARTMENTS_MEDI': {'type': 'numerical'}, 'BASEMENTAREA_MEDI': {'type': 'numerical'}, 'YEARS_BEGINEXPLUATATION_MEDI': {'type': 'numerical'}, 'YEARS_BUILD_MEDI': {'type': 'numerical'}, 'COMMONAREA_MEDI': {'type': 'numerical'}, 'ELEVATORS_MEDI': {'type': 'numerical'}, 'ENTRANCES_MEDI': {'type': 'numerical'}, 'FLOORSMAX_MEDI': {'type': 'numerical'}, 'FLOORSMIN_MEDI': {'type': 'numerical'}, 'LANDAREA_MEDI': {'type': 'numerical'}, 'LIVINGAPARTMENTS_MEDI': {'type': 'numerical'}, 'LIVINGAREA_MEDI': {'type': 'numerical'}, 'NONLIVINGAPARTMENTS_MEDI': {'type': 'numerical'}, 'NONLIVINGAREA_MEDI': {'type': 'numerical'}, 'FONDKAPREMONT_MODE': {'type': 'categorical'}, 'HOUSETYPE_MODE': {'type': 'categorical'}, 'TOTALAREA_MODE': {'type': 'numerical'}, 'WALLSMATERIAL_MODE': {'type': 'categorical'}, 'EMERGENCYSTATE_MODE': {'type': 'categorical'}, 'OBS_30_CNT_SOCIAL_CIRCLE': {'type': 'numerical'}, 'DEF_30_CNT_SOCIAL_CIRCLE': {'type': 'numerical'}, 'OBS_60_CNT_SOCIAL_CIRCLE': {'type': 'numerical'}, 'DEF_60_CNT_SOCIAL_CIRCLE': {'type': 'numerical'}, 'DAYS_LAST_PHONE_CHANGE': {'type': 'numerical'}, 'FLAG_DOCUMENT_2': {'type': 'categorical'}, 'FLAG_DOCUMENT_3': {'type': 'categorical'}, 'FLAG_DOCUMENT_4': {'type': 'categorical'}, 'FLAG_DOCUMENT_5': {'type': 'categorical'}, 'FLAG_DOCUMENT_6': {'type': 'categorical'}, 'FLAG_DOCUMENT_7': {'type': 'categorical'}, 'FLAG_DOCUMENT_8': {'type': 'categorical'}, 'FLAG_DOCUMENT_9': {'type': 'categorical'}, 'FLAG_DOCUMENT_10': {'type': 'categorical'}, 'FLAG_DOCUMENT_11': {'type': 'categorical'}, 'FLAG_DOCUMENT_12': {'type': 'categorical'}, 'FLAG_DOCUMENT_13': {'type': 'categorical'}, 'FLAG_DOCUMENT_14': {'type': 'categorical'}, 'FLAG_DOCUMENT_15': {'type': 'categorical'}, 'FLAG_DOCUMENT_16': {'type': 'categorical'}, 'FLAG_DOCUMENT_17': {'type': 'categorical'}, 'FLAG_DOCUMENT_18': {'type': 'categorical'}, 'FLAG_DOCUMENT_19': {'type': 'categorical'}, 'FLAG_DOCUMENT_20': {'type': 'categorical'}, 'FLAG_DOCUMENT_21': {'type': 'categorical'}, 'AMT_REQ_CREDIT_BUREAU_HOUR': {'type': 'numerical'}, 'AMT_REQ_CREDIT_BUREAU_DAY': {'type': 'numerical'}, 'AMT_REQ_CREDIT_BUREAU_WEEK': {'type': 'numerical'}, 'AMT_REQ_CREDIT_BUREAU_MON': {'type': 'numerical'}, 'AMT_REQ_CREDIT_BUREAU_QRT': {'type': 'numerical'}, 'AMT_REQ_CREDIT_BUREAU_YEAR': {'type': 'numerical'}}, 'bureau': {'SK_BUREAU_ID': {'type': 'categorical'}, 'CREDIT_ACTIVE': {'type': 'categorical'}, 'CREDIT_CURRENCY': {'type': 'categorical'}, 'DAYS_CREDIT': {'type': 'numerical'}, 'CREDIT_DAY_OVERDUE': {'type': 'numerical'}, 'DAYS_CREDIT_ENDDATE': {'type': 'numerical'}, 'DAYS_ENDDATE_FACT': {'type': 'numerical'}, 'AMT_CREDIT_MAX_OVERDUE': {'type': 'numerical'}, 'CNT_CREDIT_PROLONG': {'type': 'numerical'}, 'AMT_CREDIT_SUM': {'type': 'numerical'}, 'AMT_CREDIT_SUM_DEBT': {'type': 'numerical'}, 'AMT_CREDIT_SUM_LIMIT': {'type': 'numerical'}, 'AMT_CREDIT_SUM_OVERDUE': {'type': 'numerical'}, 'CREDIT_TYPE': {'type': 'categorical'}, 'DAYS_CREDIT_UPDATE': {'type': 'numerical'}}, 'bureau_balance': {'MONTHS_BALANCE': {'type': 'numerical'}, 'STATUS': {'type': 'categorical'}}, 'previous_application': {'SK_ID_PREV': {'type': 'categorical'}, 'NAME_CONTRACT_TYPE': {'type': 'categorical'}, 'AMT_ANNUITY': {'type': 'numerical'}, 'AMT_APPLICATION': {'type': 'numerical'}, 'AMT_CREDIT': {'type': 'numerical'}, 'AMT_DOWN_PAYMENT': {'type': 'numerical'}, 'AMT_GOODS_PRICE': {'type': 'numerical'}, 'WEEKDAY_APPR_PROCESS_START': {'type': 'categorical'}, 'HOUR_APPR_PROCESS_START': {'type': 'categorical'}, 'FLAG_LAST_APPL_PER_CONTRACT': {'type': 'categorical'}, 'NFLAG_LAST_APPL_IN_DAY': {'type': 'categorical'}, 'RATE_DOWN_PAYMENT': {'type': 'numerical'}, 'RATE_INTEREST_PRIMARY': {'type': 'numerical'}, 'RATE_INTEREST_PRIVILEGED': {'type': 'numerical'}, 'NAME_CASH_LOAN_PURPOSE': {'type': 'categorical'}, 'NAME_CONTRACT_STATUS': {'type': 'categorical'}, 'DAYS_DECISION': {'type': 'numerical'}, 'NAME_PAYMENT_TYPE': {'type': 'categorical'}, 'CODE_REJECT_REASON': {'type': 'categorical'}, 'NAME_TYPE_SUITE': {'type': 'categorical'}, 'NAME_CLIENT_TYPE': {'type': 'categorical'}, 'NAME_GOODS_CATEGORY': {'type': 'categorical'}, 'NAME_PORTFOLIO': {'type': 'categorical'}, 'NAME_PRODUCT_TYPE': {'type': 'categorical'}, 'CHANNEL_TYPE': {'type': 'categorical'}, 'SELLERPLACE_AREA': {'type': 'numerical'}, 'NAME_SELLER_INDUSTRY': {'type': 'categorical'}, 'CNT_PAYMENT': {'type': 'numerical'}, 'NAME_YIELD_GROUP': {'type': 'categorical'}, 'PRODUCT_COMBINATION': {'type': 'categorical'}, 'DAYS_FIRST_DRAWING': {'type': 'numerical'}, 'DAYS_FIRST_DUE': {'type': 'numerical'}, 'DAYS_LAST_DUE_1ST_VERSION': {'type': 'numerical'}, 'DAYS_LAST_DUE': {'type': 'numerical'}, 'DAYS_TERMINATION': {'type': 'numerical'}, 'NFLAG_INSURED_ON_APPROVAL': {'type': 'categorical'}}, 'POS_CASH_balance': {'SK_ID_PREV': {'type': 'categorical'}, 'MONTHS_BALANCE': {'type': 'numerical'}, 'CNT_INSTALMENT': {'type': 'numerical'}, 'CNT_INSTALMENT_FUTURE': {'type': 'numerical'}, 'NAME_CONTRACT_STATUS': {'type': 'categorical'}, 'SK_DPD': {'type': 'numerical'}, 'SK_DPD_DEF': {'type': 'numerical'}}, 'installments_payments': {'SK_ID_PREV': {'type': 'categorical'}, 'NUM_INSTALMENT_VERSION': {'type': 'numerical'}, 'NUM_INSTALMENT_NUMBER': {'type': 'numerical'}, 'DAYS_INSTALMENT': {'type': 'numerical'}, 'DAYS_ENTRY_PAYMENT': {'type': 'numerical'}, 'AMT_INSTALMENT': {'type': 'numerical'}, 'AMT_PAYMENT': {'type': 'numerical'}}, 'credit_card_balance': {'SK_ID_PREV': {'type': 'categorical'}, 'MONTHS_BALANCE': {'type': 'numerical'}, 'AMT_BALANCE': {'type': 'numerical'}, 'AMT_CREDIT_LIMIT_ACTUAL': {'type': 'numerical'}, 'AMT_DRAWINGS_ATM_CURRENT': {'type': 'numerical'}, 'AMT_DRAWINGS_CURRENT': {'type': 'numerical'}, 'AMT_DRAWINGS_OTHER_CURRENT': {'type': 'numerical'}, 'AMT_DRAWINGS_POS_CURRENT': {'type': 'numerical'}, 'AMT_INST_MIN_REGULARITY': {'type': 'numerical'}, 'AMT_PAYMENT_CURRENT': {'type': 'numerical'}, 'AMT_PAYMENT_TOTAL_CURRENT': {'type': 'numerical'}, 'AMT_RECEIVABLE_PRINCIPAL': {'type': 'numerical'}, 'AMT_RECIVABLE': {'type': 'numerical'}, 'AMT_TOTAL_RECEIVABLE': {'type': 'numerical'}, 'CNT_DRAWINGS_ATM_CURRENT': {'type': 'numerical'}, 'CNT_DRAWINGS_CURRENT': {'type': 'numerical'}, 'CNT_DRAWINGS_OTHER_CURRENT': {'type': 'numerical'}, 'CNT_DRAWINGS_POS_CURRENT': {'type': 'numerical'}, 'CNT_INSTALMENT_MATURE_CUM': {'type': 'numerical'}, 'NAME_CONTRACT_STATUS': {'type': 'categorical'}, 'SK_DPD': {'type': 'numerical'}, 'SK_DPD_DEF': {'type': 'numerical'}}}

In [13]:

def eda_per_table_printing_results(df: pd.DataFrame,schema: dict,table_name):
    results=eda_per_table(df,schema,table_name)
    for key,values in results.items() :
        print("--------------------------------------")
        print(key)
        print_dataframes(values)


def print_dataframes(dicts):
    for key,a_dataframe in dicts.items():
        print(key)
        display(a_dataframe)
    return


def eda_per_table(df: pd.DataFrame,schema: dict,table_name) -> dict :
    results={}
    for col in df.columns:
        dict_of_dataframes,column_name= eda_per_column(df,schema,table_name,col)
        results[column_name]=dict_of_dataframes
    return results


def eda_per_column(df: pd.DataFrame,schema: dict,table_name,column_name):
    dict_of_dataframes={}
    if(is_categorical(schema,table_name,column_name)):
        dict_of_dataframes= basic_eda_per_column_categorical(df,column_name)
    else:
        dict_of_dataframes=basic_eda_per_column_numerical(df,column_name) 
    return dict_of_dataframes,column_name




def is_categorical(schema: dict,table_name,column_name):
    type=schema[table_name][column_name]["type"]
    return type == "categorical"


def basic_eda_per_column_numerical(df: pd.DataFrame, column_name) -> dict: 
    column=df[column_name]
    dict_to_return={}
    basic_data_dict={}

    mean=column.mean()
    median=column.median()
    standar_deviation=column.std()

    basic_data_dict["min"]=column.min()
    basic_data_dict["max"]=column.max()
    basic_data_dict["mean"]=mean

    basic_data_dict["trim_mean"]= trim_mean(column.dropna(),proportiontocut=0.1)
    basic_data_dict["median"]= median
    basic_data_dict["standard_deviation"]=standar_deviation
    basic_data_dict["standard_error"]=column.sem()
    if(mean != 0):
        basic_data_dict["coefficient_of_variation"]= standar_deviation / abs(mean)

    basic_data_dataframe=pd.DataFrame([basic_data_dict])
    distribution_metrics_dataframe=pd.DataFrame([get_distribution_metrics(df,column_name)])

    dict_to_return["basic_data"]=basic_data_dataframe
    dict_to_return["distribution_metrics"]=distribution_metrics_dataframe

    return dict_to_return


def get_null_info(df: pd.DataFrame, column_name) -> dict:
    nulls_info={}
    
    column=df[column_name]
    column_null_maks=column.isnull()

    null_total=column_null_maks.sum()
    null_porcentaje= column_null_maks.mean() * 100

    nulls_default_rate=df[column_null_maks]
    target_correlation_nulls=nulls_default_rate["TARGET"].mean() * 100

    nulls_info["nulls_amount"]=null_total
    nulls_info["nulls_porcentaje"]=null_porcentaje
    nulls_info["default_ratio_nulls"]=target_correlation_nulls

    return nulls_info





def get_distribution_metrics(df: pd.DataFrame, column_name) -> dict:
    distribution_dict={}
    column=df[column_name]

    median= column.median()
    percentil_99=column.quantile(0.99)
    percentil_90=column.quantile(0.90)

    distribution_dict["skew"]=column.skew()
    distribution_dict["p90"]=percentil_90
    distribution_dict["p99"]=percentil_99

    if(median != 0):
        distribution_dict["ratio_p99_p50"]= percentil_99 / median
    if(percentil_90 !=0):
        distribution_dict["ratio_p99_p90"]= percentil_99 / percentil_90

    return distribution_dict
    

def basic_eda_per_column_categorical(df: pd.DataFrame,column_name) -> dict: 
    column=df[column_name]
    basic_data_dict={}
    cardinality=column.nunique(dropna=False)
    basic_data_dict["cardinality"]=cardinality
    basic_data_dict["mode"]=column.mode().to_list()
    dict_to_return={}
    dict_to_return["basic_data"]=pd.DataFrame([basic_data_dict])
    if(30 > cardinality):
        default_rate_per_category=(df.groupby(column_name,dropna=False)["TARGET"].mean() *100).reset_index(name="TARGET_RATE") 
        dict_to_return["default_rate"]=default_rate_per_category
    dict_to_return["frequency"]=get_counts_per_class(column)
    return dict_to_return


def get_counts_per_class(column : pd.Series):
    value_count_serie=column.value_counts(dropna=False)
    cardinality=value_count_serie.shape[0]
    if(cardinality < 1000):
        result_df= value_count_serie.reset_index()
        result_df.columns= ["CATEGORY", "COUNT"]
        result_df["SEGMENT"] = "full"
        return result_df
    head_df= value_count_serie.head(20).reset_index()
    head_df.columns= ["CATEGORY", "COUNT"]
    head_df["SEGMENT"] = "top"
    tail_df= value_count_serie.tail(20).reset_index()
    tail_df.columns= ["CATEGORY", "COUNT"]
    tail_df["SEGMENT"] = "bottom"
    resume_df=pd.concat([head_df,tail_df],ignore_index=True)
    return resume_df

In [8]:
eda_per_column(df,schema,"application","LOG_AMT_CREDIT")

KeyError: 'LOG_AMT_CREDIT'

In [14]:
eda_per_table_printing_results(df,schema,"application")

--------------------------------------
SK_ID_CURR
basic_data

   cardinality                                               mode
0       307511  [100002, 100003, 100004, 100006, 100007, 10000...

frequency

    CATEGORY  COUNT SEGMENT
0     100002      1     top
1     337664      1     top
2     337661      1     top
3     337660      1     top
4     337659      1     top
5     337658      1     top
6     337657      1     top
7     337656      1     top
8     337655      1     top
9     337654      1     top
10    337653      1     top
11    337652      1     top
12    337651      1     top
13    337650      1     top
14    337649      1     top
15    337648      1     top
16    337647      1     top
17    337662      1     top
18    337666      1     top
19    337645      1     top
20    218968      1  bottom
21    218985      1  bottom
22    218986      1  bottom
23    218987      1  bottom
24    218996      1  bottom
25    219004      1  bottom
26    219003      1  bottom
27    219002      1  bottom
28    218999      1  bottom
29    218998      1  bottom
30    218997      1  bottom
31    218995      1  bottom
32    218988      1  bottom
33    218994      1  bottom
34    218993      1  bottom
35    218992      1  bottom
36    218991      1  bottom
37    218990      1  bottom
38    218989      1  bottom
39    456255      1  bottom

--------------------------------------
TARGET
basic_data

   cardinality mode
0            2  [0]

default_rate

   TARGET  TARGET_RATE
0       0          0.0
1       1        100.0

frequency

   CATEGORY   COUNT SEGMENT
0         0  282686    full
1         1   24825    full

--------------------------------------
NAME_CONTRACT_TYPE
basic_data

   cardinality          mode
0            2  [Cash loans]

default_rate

  NAME_CONTRACT_TYPE  TARGET_RATE
0         Cash loans     8.345913
1    Revolving loans     5.478329

frequency

          CATEGORY   COUNT SEGMENT
0       Cash loans  278232    full
1  Revolving loans   29279    full

--------------------------------------
CODE_GENDER
basic_data

   cardinality mode
0            3  [F]

default_rate

  CODE_GENDER  TARGET_RATE
0           F     6.999328
1           M    10.141920
2         XNA     0.000000

frequency

  CATEGORY   COUNT SEGMENT
0        F  202448    full
1        M  105059    full
2      XNA       4    full

--------------------------------------
FLAG_OWN_CAR
basic_data

   cardinality mode
0            2  [N]

default_rate

  FLAG_OWN_CAR  TARGET_RATE
0            N     8.500227
1            Y     7.243730

frequency

  CATEGORY   COUNT SEGMENT
0        N  202924    full
1        Y  104587    full

--------------------------------------
FLAG_OWN_REALTY
basic_data

   cardinality mode
0            2  [Y]

default_rate

  FLAG_OWN_REALTY  TARGET_RATE
0               N     8.324929
1               Y     7.961577

frequency

  CATEGORY   COUNT SEGMENT
0        Y  213312    full
1        N   94199    full

--------------------------------------
CNT_CHILDREN
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0,19,0.417052,0.250637,0.0,0.722121,0.001302,1.731491

distribution_metrics

       skew  p90  p99  ratio_p99_p90
0  1.974604  2.0  3.0            1.5

--------------------------------------
AMT_INCOME_TOTAL
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,25650.0,117000000.0,168797.919297,155443.35938,147150.0,237123.146279,427.605833,1.404775

distribution_metrics

         skew       p90       p99  ratio_p99_p50  ratio_p99_p90
0  391.559654  270000.0  472500.0       3.211009           1.75

--------------------------------------
AMT_CREDIT
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,45000.0,4050000.0,599025.999706,548953.384998,513531.0,402490.776996,725.814442,0.671909

distribution_metrics

       skew        p90        p99  ratio_p99_p50  ratio_p99_p90
0  1.234778  1133748.0  1854000.0       3.610298       1.635284

--------------------------------------
AMT_ANNUITY
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,1615.5,258025.5,27108.573909,25656.929825,24903.0,14493.737315,26.137168,0.534655

distribution_metrics

       skew      p90      p99  ratio_p99_p50  ratio_p99_p90
0  1.579777  45954.0  70006.5       2.811167       1.523404

--------------------------------------
AMT_GOODS_PRICE
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,40500.0,4050000.0,538396.207429,489151.125737,450000.0,369446.46054,666.526743,0.686198

distribution_metrics

    skew        p90        p99  ratio_p99_p50  ratio_p99_p90
0  1.349  1093500.0  1800000.0            4.0       1.646091

--------------------------------------
NAME_TYPE_SUITE
basic_data

   cardinality             mode
0            8  [Unaccompanied]

default_rate

   NAME_TYPE_SUITE  TARGET_RATE
0         Children     7.376798
1           Family     7.494583
2  Group of people     8.487085
3          Other_A     8.775982
4          Other_B     9.830508
5  Spouse, partner     7.871592
6    Unaccompanied     8.183047
7              NaN     5.417957

frequency

          CATEGORY   COUNT SEGMENT
0    Unaccompanied  248526    full
1           Family   40149    full
2  Spouse, partner   11370    full
3         Children    3267    full
4          Other_B    1770    full
5              NaN    1292    full
6          Other_A     866    full
7  Group of people     271    full

--------------------------------------
NAME_INCOME_TYPE
basic_data

   cardinality       mode
0            8  [Working]

default_rate

       NAME_INCOME_TYPE  TARGET_RATE
0           Businessman     0.000000
1  Commercial associate     7.484257
2       Maternity leave    40.000000
3             Pensioner     5.386366
4         State servant     5.754965
5               Student     0.000000
6            Unemployed    36.363636
7               Working     9.588472

frequency

               CATEGORY   COUNT SEGMENT
0               Working  158774    full
1  Commercial associate   71617    full
2             Pensioner   55362    full
3         State servant   21703    full
4            Unemployed      22    full
5               Student      18    full
6           Businessman      10    full
7       Maternity leave       5    full

--------------------------------------
NAME_EDUCATION_TYPE
basic_data

   cardinality                             mode
0            5  [Secondary / secondary special]

default_rate

             NAME_EDUCATION_TYPE  TARGET_RATE
0                Academic degree     1.829268
1               Higher education     5.355115
2              Incomplete higher     8.484966
3                Lower secondary    10.927673
4  Secondary / secondary special     8.939929

frequency

                        CATEGORY   COUNT SEGMENT
0  Secondary / secondary special  218391    full
1               Higher education   74863    full
2              Incomplete higher   10277    full
3                Lower secondary    3816    full
4                Academic degree     164    full

--------------------------------------
NAME_FAMILY_STATUS
basic_data

   cardinality       mode
0            6  [Married]

default_rate

     NAME_FAMILY_STATUS  TARGET_RATE
0        Civil marriage     9.944584
1               Married     7.559868
2             Separated     8.194234
3  Single / not married     9.807675
4               Unknown     0.000000
5                 Widow     5.824217

frequency

               CATEGORY   COUNT SEGMENT
0               Married  196432    full
1  Single / not married   45444    full
2        Civil marriage   29775    full
3             Separated   19770    full
4                 Widow   16088    full
5               Unknown       2    full

--------------------------------------
NAME_HOUSING_TYPE
basic_data

   cardinality                 mode
0            6  [House / apartment]

default_rate

     NAME_HOUSING_TYPE  TARGET_RATE
0      Co-op apartment     7.932264
1    House / apartment     7.795711
2  Municipal apartment     8.539748
3     Office apartment     6.572411
4     Rented apartment    12.313051
5         With parents    11.698113

frequency

              CATEGORY   COUNT SEGMENT
0    House / apartment  272868    full
1         With parents   14840    full
2  Municipal apartment   11183    full
3     Rented apartment    4881    full
4     Office apartment    2617    full
5      Co-op apartment    1122    full

--------------------------------------
REGION_POPULATION_RELATIVE
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.00029,0.072508,0.020868,0.019206,0.01885,0.013831,0.000025,0.662795

distribution_metrics

       skew       p90       p99  ratio_p99_p50  ratio_p99_p90
0  1.488009  0.035792  0.072508       3.846578       2.025816

--------------------------------------
DAYS_BIRTH
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,-25229,-7489,-16036.995067,-15971.730339,-15750.0,4363.988632,7.869611,0.27212

distribution_metrics

       skew      p90     p99  ratio_p99_p50  ratio_p99_p90
0 -0.115673 -10284.0 -8263.0       0.524635       0.803481

--------------------------------------
DAYS_EMPLOYED
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,-17912,365243,63815.045904,35039.15788,-1213.0,141275.766519,254.763581,2.213832

distribution_metrics

       skew       p90       p99  ratio_p99_p50  ratio_p99_p90
0  1.664346  365243.0  365243.0    -301.107172            1.0

--------------------------------------
DAYS_REGISTRATION
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,-24672.0,0.0,-4986.120328,-4718.293363,-4504.0,3522.886321,6.352846,0.706539

distribution_metrics

       skew    p90   p99  ratio_p99_p50  ratio_p99_p90
0 -0.590872 -690.0 -50.0       0.011101       0.072464

--------------------------------------
DAYS_ID_PUBLISH
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,-7197,0,-2994.202373,-3068.299363,-3254.0,1509.450419,2.722003,0.504124

distribution_metrics

       skew    p90   p99  ratio_p99_p50  ratio_p99_p90
0  0.349327 -730.0 -61.0       0.018746       0.083562

--------------------------------------
OWN_CAR_AGE
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,91.0,12.061091,10.014187,9.0,11.944812,0.036936,0.990359

distribution_metrics

       skew   p90   p99  ratio_p99_p50  ratio_p99_p90
0  2.745422  22.0  64.0       7.111111       2.909091

--------------------------------------
FLAG_MOBIL
basic_data

   cardinality mode
0            2  [1]

default_rate

   FLAG_MOBIL  TARGET_RATE
0           0     0.000000
1           1     8.072908

frequency

   CATEGORY   COUNT SEGMENT
0         1  307510    full
1         0       1    full

--------------------------------------
FLAG_EMP_PHONE
basic_data

   cardinality mode
0            2  [1]

default_rate

   FLAG_EMP_PHONE  TARGET_RATE
0               0     5.400282
1               1     8.659990

frequency

   CATEGORY   COUNT SEGMENT
0         1  252125    full
1         0   55386    full

--------------------------------------
FLAG_WORK_PHONE
basic_data

   cardinality mode
0            2  [0]

default_rate

   FLAG_WORK_PHONE  TARGET_RATE
0                0     7.685122
1                1     9.630065

frequency

   CATEGORY   COUNT SEGMENT
0         0  246203    full
1         1   61308    full

--------------------------------------
FLAG_CONT_MOBILE
basic_data

   cardinality mode
0            2  [1]

default_rate

   FLAG_CONT_MOBILE  TARGET_RATE
0                 0     7.839721
1                 1     8.073318

frequency

   CATEGORY   COUNT SEGMENT
0         1  306937    full
1         0     574    full

--------------------------------------
FLAG_PHONE
basic_data

   cardinality mode
0            2  [0]

default_rate

   FLAG_PHONE  TARGET_RATE
0           0     8.478379
1           1     7.035670

frequency

   CATEGORY   COUNT SEGMENT
0         0  221080    full
1         1   86431    full

--------------------------------------
FLAG_EMAIL
basic_data

   cardinality mode
0            2  [0]

default_rate

   FLAG_EMAIL  TARGET_RATE
0           0     8.084628
1           1     7.877537

frequency

   CATEGORY   COUNT SEGMENT
0         0  290069    full
1         1   17442    full

--------------------------------------
OCCUPATION_TYPE
basic_data

   cardinality        mode
0           19  [Laborers]

default_rate

          OCCUPATION_TYPE  TARGET_RATE
0             Accountants     4.830327
1          Cleaning staff     9.606705
2           Cooking staff    10.443996
3              Core staff     6.303954
4                 Drivers    11.326130
5                HR staff     6.394316
6   High skill tech staff     6.159930
7                IT staff     6.463878
8                Laborers    10.578770
9      Low-skill Laborers    17.152413
10               Managers     6.214028
11         Medicine staff     6.700246
12  Private service staff     6.598793
13          Realty agents     7.856192
14            Sales staff     9.631799
15            Secretaries     7.049808
16         Security staff    10.742449
17   Waiters/barmen staff    11.275964
18                    NaN     6.513056

frequency

                 CATEGORY  COUNT SEGMENT
0                     NaN  96391    full
1                Laborers  55186    full
2             Sales staff  32102    full
3              Core staff  27570    full
4                Managers  21371    full
5                 Drivers  18603    full
6   High skill tech staff  11380    full
7             Accountants   9813    full
8          Medicine staff   8537    full
9          Security staff   6721    full
10          Cooking staff   5946    full
11         Cleaning staff   4653    full
12  Private service staff   2652    full
13     Low-skill Laborers   2093    full
14   Waiters/barmen staff   1348    full
15            Secretaries   1305    full
16          Realty agents    751    full
17               HR staff    563    full
18               IT staff    526    full

--------------------------------------
CNT_FAM_MEMBERS
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,1.0,20.0,2.152665,2.054705,2.0,0.910682,0.001642,0.423048

distribution_metrics

       skew  p90  p99  ratio_p99_p50  ratio_p99_p90
0  0.987543  3.0  5.0            2.5       1.666667

--------------------------------------
REGION_RATING_CLIENT
basic_data

   cardinality mode
0            3  [2]

default_rate

   REGION_RATING_CLIENT  TARGET_RATE
0                     1     4.820325
1                     2     7.889102
2                     3    11.102835

frequency

   CATEGORY   COUNT SEGMENT
0         2  226984    full
1         3   48330    full
2         1   32197    full

--------------------------------------
REGION_RATING_CLIENT_W_CITY
basic_data

   cardinality mode
0            3  [2]

default_rate

   REGION_RATING_CLIENT_W_CITY  TARGET_RATE
0                            1     4.840928
1                            2     7.917763
2                            3    11.402189

frequency

   CATEGORY   COUNT SEGMENT
0         2  229484    full
1         3   43860    full
2         1   34167    full

--------------------------------------
WEEKDAY_APPR_PROCESS_START
basic_data

   cardinality       mode
0            7  [TUESDAY]

default_rate

  WEEKDAY_APPR_PROCESS_START  TARGET_RATE
0                     FRIDAY     8.146927
1                     MONDAY     7.757227
2                   SATURDAY     7.887274
3                     SUNDAY     7.929053
4                   THURSDAY     8.100255
5                    TUESDAY     8.350494
6                  WEDNESDAY     8.160357

frequency

    CATEGORY  COUNT SEGMENT
0    TUESDAY  53901    full
1  WEDNESDAY  51934    full
2     MONDAY  50714    full
3   THURSDAY  50591    full
4     FRIDAY  50338    full
5   SATURDAY  33852    full
6     SUNDAY  16181    full

--------------------------------------
HOUR_APPR_PROCESS_START
basic_data

   cardinality  mode
0           24  [10]

default_rate

    HOUR_APPR_PROCESS_START  TARGET_RATE
0                         0    15.000000
1                         1     8.139535
2                         2     9.836066
3                         3     8.699187
4                         4     8.277512
5                         5    10.582738
6                         6    11.040739
7                         7    10.042712
8                         8     9.076486
9                         9     8.205521
10                       10     8.021844
11                       11     8.074351
12                       12     8.258114
13                       13     8.026745
14                       14     7.907666
15                       15     7.592898
16                       16     7.461369
17                       17     6.489933
18                       18     7.017350
19                       19     6.860707
20                       20     7.023411
21                       21     6.172840
22                       22    10.000000
23                       23    12.195122

frequency

    CATEGORY  COUNT SEGMENT
0         10  37722    full
1         11  37229    full
2         12  34233    full
3         13  30959    full
4         14  27682    full
5          9  27384    full
6         15  24839    full
7         16  20385    full
8          8  15127    full
9         17  14900    full
10         7   9131    full
11        18   9049    full
12         6   5842    full
13        19   3848    full
14         5   3638    full
15         4   2090    full
16         3   1230    full
17        20   1196    full
18        21    405    full
19         2    305    full
20        22    150    full
21         1     86    full
22        23     41    full
23         0     40    full

--------------------------------------
REG_REGION_NOT_LIVE_REGION
basic_data

   cardinality mode
0            2  [0]

default_rate

   REG_REGION_NOT_LIVE_REGION  TARGET_RATE
0                           0     8.054046
1                           1     9.297831

frequency

   CATEGORY   COUNT SEGMENT
0         0  302854    full
1         1    4657    full

--------------------------------------
REG_REGION_NOT_WORK_REGION
basic_data

   cardinality mode
0            2  [0]

default_rate

   REG_REGION_NOT_WORK_REGION  TARGET_RATE
0                           0     8.029147
1                           1     8.890597

frequency

   CATEGORY   COUNT SEGMENT
0         0  291899    full
1         1   15612    full

--------------------------------------
LIVE_REGION_NOT_WORK_REGION
basic_data

   cardinality mode
0            2  [0]

default_rate

   LIVE_REGION_NOT_WORK_REGION  TARGET_RATE
0                            0     8.057070
1                            1     8.445973

frequency

   CATEGORY   COUNT SEGMENT
0         0  295008    full
1         1   12503    full

--------------------------------------
REG_CITY_NOT_LIVE_CITY
basic_data

   cardinality mode
0            2  [0]

default_rate

   REG_CITY_NOT_LIVE_CITY  TARGET_RATE
0                       0     7.720692
1                       1    12.225966

frequency

   CATEGORY   COUNT SEGMENT
0         0  283472    full
1         1   24039    full

--------------------------------------
REG_CITY_NOT_WORK_CITY
basic_data

   cardinality mode
0            2  [0]

default_rate

   REG_CITY_NOT_WORK_CITY  TARGET_RATE
0                       0     7.312672
1                       1    10.611427

frequency

   CATEGORY   COUNT SEGMENT
0         0  236644    full
1         1   70867    full

--------------------------------------
LIVE_CITY_NOT_WORK_CITY
basic_data

   cardinality mode
0            2  [0]

default_rate

   LIVE_CITY_NOT_WORK_CITY  TARGET_RATE
0                        0     7.658465
1                        1     9.966495

frequency

   CATEGORY   COUNT SEGMENT
0         0  252296    full
1         1   55215    full

--------------------------------------
ORGANIZATION_TYPE
basic_data

   cardinality                      mode
0           58  [Business Entity Type 3]

frequency

                  CATEGORY  COUNT SEGMENT
0   Business Entity Type 3  67992    full
1                      XNA  55374    full
2            Self-employed  38412    full
3                    Other  16683    full
4                 Medicine  11193    full
5   Business Entity Type 2  10553    full
6               Government  10404    full
7                   School   8893    full
8            Trade: type 7   7831    full
9             Kindergarten   6880    full
10            Construction   6721    full
11  Business Entity Type 1   5984    full
12       Transport: type 4   5398    full
13           Trade: type 3   3492    full
14        Industry: type 9   3368    full
15        Industry: type 3   3278    full
16                Security   3247    full
17                 Housing   2958    full
18       Industry: type 11   2704    full
19                Military   2634    full
20                    Bank   2507    full
21             Agriculture   2454    full
22                  Police   2341    full
23       Transport: type 2   2204    full
24                  Postal   2157    full
25     Security Ministries   1974    full
26           Trade: type 2   1900    full
27              Restaurant   1811    full
28                Services   1575    full
29              University   1327    full
30        Industry: type 7   1307    full
31       Transport: type 3   1187    full
32        Industry: type 1   1039    full
33                   Hotel    966    full
34             Electricity    950    full
35        Industry: type 4    877    full
36           Trade: type 6    631    full
37        Industry: type 5    599    full
38               Insurance    597    full
39                 Telecom    577    full
40               Emergency    560    full
41        Industry: type 2    458    full
42             Advertising    429    full
43                 Realtor    396    full
44                 Culture    379    full
45       Industry: type 12    369    full
46           Trade: type 1    348    full
47                  Mobile    317    full
48          Legal Services    305    full
49                Cleaning    260    full
50       Transport: type 1    201    full
51        Industry: type 6    112    full
52       Industry: type 10    109    full
53                Religion     85    full
54       Industry: type 13     67    full
55           Trade: type 4     64    full
56           Trade: type 5     49    full
57        Industry: type 8     24    full

--------------------------------------
EXT_SOURCE_1
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.014568,0.962693,0.50213,0.504179,0.505998,0.211062,0.000576,0.420334

distribution_metrics

       skew       p90       p99  ratio_p99_p50  ratio_p99_p90
0 -0.068755  0.786664  0.889411       1.757736       1.130611

--------------------------------------
EXT_SOURCE_2
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,8.173617e-08,0.855,0.514393,0.533778,0.565961,0.19106,0.000345,0.371429

distribution_metrics

       skew       p90       p99  ratio_p99_p50  ratio_p99_p90
0 -0.793576  0.722047  0.782793        1.38312        1.08413

--------------------------------------
EXT_SOURCE_3
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.000527,0.89601,0.510853,0.521212,0.535276,0.194844,0.000392,0.38141

distribution_metrics

      skew       p90       p99  ratio_p99_p50  ratio_p99_p90
0 -0.40939  0.749022  0.832785       1.555804        1.11183

--------------------------------------
APARTMENTS_AVG
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,1.0,0.11744,0.099671,0.0876,0.10824,0.000278,0.921661

distribution_metrics

       skew     p90       p99  ratio_p99_p50  ratio_p99_p90
0  2.641836  0.2412  0.544861       6.219874       2.258959

--------------------------------------
BASEMENTAREA_AVG
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,1.0,0.088442,0.077438,0.0763,0.082438,0.000231,0.932113

distribution_metrics

       skew     p90       p99  ratio_p99_p50  ratio_p99_p90
0  3.566306  0.1685  0.385966       5.058532       2.290599

--------------------------------------
YEARS_BEGINEXPLUATATION_AVG
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,1.0,0.977735,0.981751,0.9816,0.059223,0.000149,0.060572

distribution_metrics

        skew     p90    p99  ratio_p99_p50  ratio_p99_p90
0 -15.515264  0.9911  0.999       1.017726       1.007971

--------------------------------------
YEARS_BUILD_AVG
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,1.0,0.752471,0.754785,0.7552,0.11328,0.000353,0.150544

distribution_metrics

       skew     p90     p99  ratio_p99_p50  ratio_p99_p90
0 -0.962485  0.8776  0.9864       1.306144       1.123974

--------------------------------------
COMMONAREA_AVG
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,1.0,0.044621,0.029315,0.0211,0.076036,0.00025,1.704046

distribution_metrics

       skew     p90       p99  ratio_p99_p50  ratio_p99_p90
0  5.457305  0.1053  0.376555      17.846209       3.576021

--------------------------------------
ELEVATORS_AVG
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,1.0,0.078942,0.049035,0.0,0.134576,0.000355,1.704756

distribution_metrics

       skew   p90  p99  ratio_p99_p90
0  2.439429  0.24  0.6            2.5

--------------------------------------
ENTRANCES_AVG
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,1.0,0.149725,0.137499,0.1379,0.100049,0.000256,0.668221

distribution_metrics

       skew     p90     p99  ratio_p99_p50  ratio_p99_p90
0  2.399717  0.2759  0.5172       3.750544       1.874592

--------------------------------------
FLOORSMAX_AVG
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,1.0,0.226282,0.213315,0.1667,0.144641,0.000368,0.639206

distribution_metrics

       skew    p90     p99  ratio_p99_p50  ratio_p99_p90
0  1.226454  0.375  0.6667         3.9994       1.777867

--------------------------------------
FLOORSMIN_AVG
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,1.0,0.231894,0.216986,0.2083,0.16138,0.000513,0.695924

distribution_metrics

       skew     p90     p99  ratio_p99_p50  ratio_p99_p90
0  0.954197  0.4167  0.7083       3.400384       1.699784

--------------------------------------
LANDAREA_AVG
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,1.0,0.066333,0.052704,0.0481,0.081184,0.00023,1.223877

distribution_metrics

       skew     p90     p99  ratio_p99_p50  ratio_p99_p90
0  4.458677  0.1406  0.3746       7.787942       2.664296

--------------------------------------
LIVINGAPARTMENTS_AVG
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,1.0,0.100775,0.085522,0.0756,0.092576,0.000297,0.918644

distribution_metrics

       skew     p90     p99  ratio_p99_p50  ratio_p99_p90
0  3.042198  0.2059  0.4539       6.003968       2.204468

--------------------------------------
LIVINGAREA_AVG
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,1.0,0.107399,0.087357,0.0745,0.110565,0.000283,1.029474

distribution_metrics

       skew     p90     p99  ratio_p99_p50  ratio_p99_p90
0  2.854736  0.2327  0.5509       7.394631       2.367426

--------------------------------------
NONLIVINGAPARTMENTS_AVG
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,1.0,0.008809,0.002606,0.0,0.047732,0.000156,5.418712

distribution_metrics

        skew     p90     p99  ratio_p99_p90
0  15.541185  0.0154  0.1081       7.019481

--------------------------------------
NONLIVINGAREA_AVG
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,1.0,0.028358,0.013249,0.0036,0.069523,0.000187,2.451646

distribution_metrics

       skew     p90     p99  ratio_p99_p50  ratio_p99_p90
0  6.559012  0.0806  0.3165      87.916667       3.926799

--------------------------------------
APARTMENTS_MODE
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,1.0,0.114231,0.096166,0.084,0.107936,0.000277,0.944893

distribution_metrics

       skew     p90    p99  ratio_p99_p50  ratio_p99_p90
0  2.703052  0.2311  0.541       6.440476       2.340978

--------------------------------------
BASEMENTAREA_MODE
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,1.0,0.087543,0.075831,0.0746,0.084307,0.000236,0.963035

distribution_metrics

       skew     p90     p99  ratio_p99_p50  ratio_p99_p90
0  3.481533  0.1696  0.3962       5.310992       2.336085

--------------------------------------
YEARS_BEGINEXPLUATATION_MODE
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,1.0,0.977065,0.981529,0.9816,0.064575,0.000163,0.066091

distribution_metrics

        skew     p90    p99  ratio_p99_p50  ratio_p99_p90
0 -14.755318  0.9906  0.999       1.017726        1.00848

--------------------------------------
YEARS_BUILD_MODE
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,1.0,0.759637,0.7619,0.7648,0.110111,0.000343,0.144952

distribution_metrics

       skew     p90     p99  ratio_p99_p50  ratio_p99_p90
0 -1.002305  0.8824  0.9869       1.290403       1.118427

--------------------------------------
COMMONAREA_MODE
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,1.0,0.042553,0.027533,0.019,0.074445,0.000245,1.749448

distribution_metrics

       skew     p90       p99  ratio_p99_p50  ratio_p99_p90
0  5.620589  0.1008  0.365555      19.239737       3.626538

--------------------------------------
ELEVATORS_MODE
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,1.0,0.07449,0.044578,0.0,0.132256,0.000349,1.775495

distribution_metrics

       skew     p90     p99  ratio_p99_p90
0  2.552281  0.2417  0.6042       2.499793

--------------------------------------
ENTRANCES_MODE
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,1.0,0.145193,0.132101,0.1379,0.100977,0.000258,0.695469

distribution_metrics

       skew     p90     p99  ratio_p99_p50  ratio_p99_p90
0  2.392343  0.2759  0.5172       3.750544       1.874592

--------------------------------------
FLOORSMAX_MODE
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,1.0,0.222315,0.209601,0.1667,0.143709,0.000366,0.646422

distribution_metrics

       skew    p90     p99  ratio_p99_p50  ratio_p99_p90
0  1.244343  0.375  0.6667         3.9994       1.777867

--------------------------------------
FLOORSMIN_MODE
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,1.0,0.228058,0.213008,0.2083,0.16116,0.000513,0.70666

distribution_metrics

       skew     p90     p99  ratio_p99_p50  ratio_p99_p90
0  0.963835  0.4167  0.7083       3.400384       1.699784

--------------------------------------
LANDAREA_MODE
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,1.0,0.064958,0.050846,0.0458,0.08175,0.000231,1.258516

distribution_metrics

       skew     p90      p99  ratio_p99_p50  ratio_p99_p90
0  4.377027  0.1409  0.37888       8.272489       2.688999

--------------------------------------
LIVINGAPARTMENTS_MODE
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,1.0,0.105645,0.089181,0.0771,0.09788,0.000314,0.926505

distribution_metrics

       skew     p90     p99  ratio_p99_p50  ratio_p99_p90
0  2.902672  0.2167  0.4885       6.335927       2.254269

--------------------------------------
LIVINGAREA_MODE
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,1.0,0.105975,0.085243,0.0731,0.111845,0.000286,1.055392

distribution_metrics

       skew     p90      p99  ratio_p99_p50  ratio_p99_p90
0  2.902491  0.2336  0.56164       7.683174       2.404281

--------------------------------------
NONLIVINGAPARTMENTS_MODE
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,1.0,0.008076,0.002207,0.0,0.046276,0.000151,5.729822

distribution_metrics

        skew     p90     p99  ratio_p99_p90
0  16.251819  0.0156  0.0973       6.237179

--------------------------------------
NONLIVINGAREA_MODE
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,1.0,0.027022,0.011361,0.0011,0.070254,0.000189,2.599846

distribution_metrics

       skew     p90     p99  ratio_p99_p50  ratio_p99_p90
0  6.522451  0.0788  0.3221     292.818182       4.087563

--------------------------------------
APARTMENTS_MEDI
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,1.0,0.11785,0.09982,0.0864,0.109076,0.00028,0.925549

distribution_metrics

       skew    p90      p99  ratio_p99_p50  ratio_p99_p90
0  2.639256  0.242  0.55011       6.367014       2.273182

--------------------------------------
BASEMENTAREA_MEDI
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,1.0,0.087955,0.076943,0.0758,0.082179,0.00023,0.934329

distribution_metrics

      skew     p90     p99  ratio_p99_p50  ratio_p99_p90
0  3.55304  0.1678  0.3845       5.072559       2.291418

--------------------------------------
YEARS_BEGINEXPLUATATION_MEDI
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,1.0,0.977752,0.98174,0.9816,0.059897,0.000151,0.06126

distribution_metrics

        skew     p90    p99  ratio_p99_p50  ratio_p99_p90
0 -15.573124  0.9911  0.999       1.017726       1.007971

--------------------------------------
YEARS_BUILD_MEDI
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,1.0,0.755746,0.757914,0.7585,0.112066,0.000349,0.148286

distribution_metrics

       skew     p90     p99  ratio_p99_p50  ratio_p99_p90
0 -0.962784  0.8792  0.9866       1.300725       1.122157

--------------------------------------
COMMONAREA_MEDI
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,1.0,0.044595,0.029213,0.0208,0.076144,0.00025,1.707458

distribution_metrics

       skew     p90       p99  ratio_p99_p50  ratio_p99_p90
0  5.419238  0.1053  0.378555       18.19976       3.595014

--------------------------------------
ELEVATORS_MEDI
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,1.0,0.078078,0.048069,0.0,0.134467,0.000355,1.722219

distribution_metrics

       skew   p90  p99  ratio_p99_p90
0  2.457824  0.24  0.6            2.5

--------------------------------------
ENTRANCES_MEDI
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,1.0,0.149213,0.136852,0.1379,0.100368,0.000257,0.672653

distribution_metrics

       skew     p90     p99  ratio_p99_p50  ratio_p99_p90
0  2.387711  0.2759  0.5172       3.750544       1.874592

--------------------------------------
FLOORSMAX_MEDI
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,1.0,0.225897,0.212771,0.1667,0.145067,0.000369,0.642183

distribution_metrics

       skew    p90     p99  ratio_p99_p50  ratio_p99_p90
0  1.240185  0.375  0.6667         3.9994       1.777867

--------------------------------------
FLOORSMIN_MEDI
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,1.0,0.231625,0.216547,0.2083,0.161934,0.000515,0.69912

distribution_metrics

       skew     p90     p99  ratio_p99_p50  ratio_p99_p90
0  0.960226  0.4167  0.7083       3.400384       1.699784

--------------------------------------
LANDAREA_MEDI
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,1.0,0.067169,0.053304,0.0487,0.082167,0.000232,1.223292

distribution_metrics

       skew     p90      p99  ratio_p99_p50  ratio_p99_p90
0  4.368292  0.1428  0.38128       7.829158       2.670028

--------------------------------------
LIVINGAPARTMENTS_MEDI
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,1.0,0.101954,0.086424,0.0761,0.093642,0.0003,0.918472

distribution_metrics

       skew     p90     p99  ratio_p99_p50  ratio_p99_p90
0  2.988291  0.2086  0.4617       6.067017       2.213327

--------------------------------------
LIVINGAREA_MEDI
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,1.0,0.108607,0.088122,0.0749,0.11226,0.000287,1.03364

distribution_metrics

       skew    p90     p99  ratio_p99_p50  ratio_p99_p90
0  2.848935  0.236  0.5581       7.451268       2.364831

--------------------------------------
NONLIVINGAPARTMENTS_MEDI
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,1.0,0.008651,0.002511,0.0,0.047415,0.000155,5.480829

distribution_metrics

        skew     p90     p99  ratio_p99_p90
0  15.671995  0.0155  0.1048        6.76129

--------------------------------------
NONLIVINGAREA_MEDI
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,1.0,0.028236,0.012865,0.0031,0.070166,0.000189,2.485008

distribution_metrics

       skew      p90       p99  ratio_p99_p50  ratio_p99_p90
0  6.508831  0.08102  0.321272     103.636129       3.965342

--------------------------------------
FONDKAPREMONT_MODE
basic_data

   cardinality                mode
0            5  [reg oper account]

default_rate

      FONDKAPREMONT_MODE  TARGET_RATE
0          not specified     7.543520
1       org spec account     5.819541
2       reg oper account     6.978193
3  reg oper spec account     6.556291
4                    NaN     8.618845

frequency

                CATEGORY   COUNT SEGMENT
0                    NaN  210295    full
1       reg oper account   73830    full
2  reg oper spec account   12080    full
3          not specified    5687    full
4       org spec account    5619    full

--------------------------------------
HOUSETYPE_MODE
basic_data

   cardinality              mode
0            4  [block of flats]

default_rate

     HOUSETYPE_MODE  TARGET_RATE
0    block of flats     6.943383
1  specific housing    10.140093
2    terraced house     8.498350
3               NaN     9.151182

frequency

           CATEGORY   COUNT SEGMENT
0               NaN  154297    full
1    block of flats  150503    full
2  specific housing    1499    full
3    terraced house    1212    full

--------------------------------------
TOTALAREA_MODE
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,1.0,0.102547,0.083152,0.0688,0.107462,0.000269,1.047936

distribution_metrics

       skew     p90     p99  ratio_p99_p50  ratio_p99_p90
0  2.797572  0.2273  0.5258       7.642442       2.313242

--------------------------------------
WALLSMATERIAL_MODE
basic_data

   cardinality     mode
0            8  [Panel]

default_rate

  WALLSMATERIAL_MODE  TARGET_RATE
0              Block     7.024749
1              Mixed     7.534843
2         Monolithic     4.721754
3             Others     8.307692
4              Panel     6.347668
5       Stone, brick     7.405693
6             Wooden     9.697874
7                NaN     9.128124

frequency

       CATEGORY   COUNT SEGMENT
0           NaN  156341    full
1         Panel   66040    full
2  Stone, brick   64815    full
3         Block    9253    full
4        Wooden    5362    full
5         Mixed    2296    full
6    Monolithic    1779    full
7        Others    1625    full

--------------------------------------
EMERGENCYSTATE_MODE
basic_data

   cardinality  mode
0            3  [No]

default_rate

  EMERGENCYSTATE_MODE  TARGET_RATE
0                  No     6.964900
1                 Yes     9.579038
2                 NaN     9.260746

frequency

  CATEGORY   COUNT SEGMENT
0       No  159428    full
1      NaN  145755    full
2      Yes    2328    full

--------------------------------------
OBS_30_CNT_SOCIAL_CIRCLE
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,348.0,1.422245,0.903117,0.0,2.400989,0.004337,1.688168

distribution_metrics

        skew  p90   p99  ratio_p99_p90
0  12.139598  4.0  10.0            2.5

--------------------------------------
DEF_30_CNT_SOCIAL_CIRCLE
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,34.0,0.143421,0.018422,0.0,0.446698,0.000807,3.114603

distribution_metrics

       skew  p90  p99  ratio_p99_p90
0  5.183518  1.0  2.0            2.0

--------------------------------------
OBS_60_CNT_SOCIAL_CIRCLE
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,344.0,1.405292,0.890498,0.0,2.379803,0.004299,1.693458

distribution_metrics

        skew  p90   p99  ratio_p99_p90
0  12.070829  4.0  10.0            2.5

--------------------------------------
DEF_60_CNT_SOCIAL_CIRCLE
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,24.0,0.100049,0.0,0.0,0.362291,0.000654,3.621136

distribution_metrics

       skew  p90  p99
0  5.277878  0.0  2.0

--------------------------------------
DAYS_LAST_PHONE_CHANGE
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,-4292.0,0.0,-962.858788,-877.691047,-757.0,826.808487,1.490992,0.858702

distribution_metrics

       skew  p90  p99  ratio_p99_p50
0 -0.713606  0.0  0.0           -0.0

--------------------------------------
FLAG_DOCUMENT_2
basic_data

   cardinality mode
0            2  [0]

default_rate

   FLAG_DOCUMENT_2  TARGET_RATE
0                0     8.071922
1                1    30.769231

frequency

   CATEGORY   COUNT SEGMENT
0         0  307498    full
1         1      13    full

--------------------------------------
FLAG_DOCUMENT_3
basic_data

   cardinality mode
0            2  [1]

default_rate

   FLAG_DOCUMENT_3  TARGET_RATE
0                0     6.182503
1                1     8.844921

frequency

   CATEGORY   COUNT SEGMENT
0         1  218340    full
1         0   89171    full

--------------------------------------
FLAG_DOCUMENT_4
basic_data

   cardinality mode
0            2  [0]

default_rate

   FLAG_DOCUMENT_4  TARGET_RATE
0                0     8.073538
1                1     0.000000

frequency

   CATEGORY   COUNT SEGMENT
0         0  307486    full
1         1      25    full

--------------------------------------
FLAG_DOCUMENT_5
basic_data

   cardinality mode
0            2  [0]

default_rate

   FLAG_DOCUMENT_5  TARGET_RATE
0                0     8.073948
1                1     8.003442

frequency

   CATEGORY   COUNT SEGMENT
0         0  302863    full
1         1    4648    full

--------------------------------------
FLAG_DOCUMENT_6
basic_data

   cardinality mode
0            2  [0]

default_rate

   FLAG_DOCUMENT_6  TARGET_RATE
0                0     8.314999
1                1     5.565404

frequency

   CATEGORY   COUNT SEGMENT
0         0  280433    full
1         1   27078    full

--------------------------------------
FLAG_DOCUMENT_7
basic_data

   cardinality mode
0            2  [0]

default_rate

   FLAG_DOCUMENT_7  TARGET_RATE
0                0     8.073455
1                1     5.084746

frequency

   CATEGORY   COUNT SEGMENT
0         0  307452    full
1         1      59    full

--------------------------------------
FLAG_DOCUMENT_8
basic_data

   cardinality mode
0            2  [0]

default_rate

   FLAG_DOCUMENT_8  TARGET_RATE
0                0     8.138074
1                1     7.336957

frequency

   CATEGORY   COUNT SEGMENT
0         0  282487    full
1         1   25024    full

--------------------------------------
FLAG_DOCUMENT_9
basic_data

   cardinality mode
0            2  [0]

default_rate

   FLAG_DOCUMENT_9  TARGET_RATE
0                0     8.080297
1                1     6.176962

frequency

   CATEGORY   COUNT SEGMENT
0         0  306313    full
1         1    1198    full

--------------------------------------
FLAG_DOCUMENT_10
basic_data

   cardinality mode
0            2  [0]

default_rate

   FLAG_DOCUMENT_10  TARGET_RATE
0                 0     8.073066
1                 1     0.000000

frequency

   CATEGORY   COUNT SEGMENT
0         0  307504    full
1         1       7    full

--------------------------------------
FLAG_DOCUMENT_11
basic_data

   cardinality mode
0            2  [0]

default_rate

   FLAG_DOCUMENT_11  TARGET_RATE
0                 0     8.080102
1                 1     6.234414

frequency

   CATEGORY   COUNT SEGMENT
0         0  306308    full
1         1    1203    full

--------------------------------------
FLAG_DOCUMENT_12
basic_data

   cardinality mode
0            2  [0]

default_rate

   FLAG_DOCUMENT_12  TARGET_RATE
0                 0     8.072934
1                 1     0.000000

frequency

   CATEGORY   COUNT SEGMENT
0         0  307509    full
1         1       2    full

--------------------------------------
FLAG_DOCUMENT_13
basic_data

   cardinality mode
0            2  [0]

default_rate

   FLAG_DOCUMENT_13  TARGET_RATE
0                 0     8.091650
1                 1     2.767528

frequency

   CATEGORY   COUNT SEGMENT
0         0  306427    full
1         1    1084    full

--------------------------------------
FLAG_DOCUMENT_14
basic_data

   cardinality mode
0            2  [0]

default_rate

   FLAG_DOCUMENT_14  TARGET_RATE
0                 0     8.086873
1                 1     3.322259

frequency

   CATEGORY   COUNT SEGMENT
0         0  306608    full
1         1     903    full

--------------------------------------
FLAG_DOCUMENT_15
basic_data

   cardinality mode
0            2  [0]

default_rate

   FLAG_DOCUMENT_15  TARGET_RATE
0                 0     8.079078
1                 1     2.956989

frequency

   CATEGORY   COUNT SEGMENT
0         0  307139    full
1         1     372    full

--------------------------------------
FLAG_DOCUMENT_16
basic_data

   cardinality mode
0            2  [0]

default_rate

   FLAG_DOCUMENT_16  TARGET_RATE
0                 0     8.104566
1                 1     4.913200

frequency

   CATEGORY   COUNT SEGMENT
0         0  304458    full
1         1    3053    full

--------------------------------------
FLAG_DOCUMENT_17
basic_data

   cardinality mode
0            2  [0]

default_rate

   FLAG_DOCUMENT_17  TARGET_RATE
0                 0     8.074385
1                 1     2.439024

frequency

   CATEGORY   COUNT SEGMENT
0         0  307429    full
1         1      82    full

--------------------------------------
FLAG_DOCUMENT_18
basic_data

   cardinality mode
0            2  [0]

default_rate

   FLAG_DOCUMENT_18  TARGET_RATE
0                 0     8.092495
1                 1     5.680000

frequency

   CATEGORY   COUNT SEGMENT
0         0  305011    full
1         1    2500    full

--------------------------------------
FLAG_DOCUMENT_19
basic_data

   cardinality mode
0            2  [0]

default_rate

   FLAG_DOCUMENT_19  TARGET_RATE
0                 0     8.073784
1                 1     6.557377

frequency

   CATEGORY   COUNT SEGMENT
0         0  307328    full
1         1     183    full

--------------------------------------
FLAG_DOCUMENT_20
basic_data

   cardinality mode
0            2  [0]

default_rate

   FLAG_DOCUMENT_20  TARGET_RATE
0                 0     8.072750
1                 1     8.333333

frequency

   CATEGORY   COUNT SEGMENT
0         0  307355    full
1         1     156    full

--------------------------------------
FLAG_DOCUMENT_21
basic_data

   cardinality mode
0            2  [0]

default_rate

   FLAG_DOCUMENT_21  TARGET_RATE
0                 0     8.071033
1                 1    13.592233

frequency

   CATEGORY   COUNT SEGMENT
0         0  307408    full
1         1     103    full

--------------------------------------
AMT_REQ_CREDIT_BUREAU_HOUR
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,4.0,0.006402,0.0,0.0,0.083849,0.000163,13.096417

distribution_metrics

        skew  p90  p99
0  14.534062  0.0  0.0

--------------------------------------
AMT_REQ_CREDIT_BUREAU_DAY
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,9.0,0.007,0.0,0.0,0.110757,0.000215,15.822011

distribution_metrics

        skew  p90  p99
0  27.043505  0.0  0.0

--------------------------------------
AMT_REQ_CREDIT_BUREAU_WEEK
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,8.0,0.034362,0.0,0.0,0.204685,0.000397,5.956733

distribution_metrics

       skew  p90  p99
0  9.293573  0.0  1.0

--------------------------------------
AMT_REQ_CREDIT_BUREAU_MON
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,27.0,0.267395,0.080641,0.0,0.916002,0.001776,3.425649

distribution_metrics

       skew  p90  p99  ratio_p99_p90
0  7.804848  1.0  4.0            4.0

--------------------------------------
AMT_REQ_CREDIT_BUREAU_QRT
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,261.0,0.265474,0.112672,0.0,0.794056,0.00154,2.991085

distribution_metrics

         skew  p90  p99  ratio_p99_p90
0  134.365776  1.0  2.0            2.0

--------------------------------------
AMT_REQ_CREDIT_BUREAU_YEAR
basic_data

,min,max,mean,trim_mean,median,standard_deviation,standard_error,coefficient_of_variation
0,0.0,25.0,1.899974,1.626648,1.0,1.869295,0.003624,0.983853

distribution_metrics

      skew  p90  p99  ratio_p99_p50  ratio_p99_p90
0  1.24359  4.0  8.0            8.0            2.0

In [ ]:
create_files_nulls_per_colmun(df,"aplication_train")

print(len(df))

In [ ]:

#now we will explore the hypothesis of train one model per type of contract. Starting for how viable is with the data available

print(df["NAME_CONTRACT_TYPE"].value_counts(normalize=True) * 100)
print(df.groupby("NAME_CONTRACT_TYPE")["TARGET"].mean() * 100)

#Considering the volume of the minoritary class (less than 10%) and their event ratio (5%) seems not ideal have to separate the models.

In [ ]:
#here i want to check if the main variables that describes the loan change their distribution and trending between the type of contract,
#and also see how much change in the case of default. 

df["LOG_AMT_CREDIT"]= np.log10(df["AMT_CREDIT"])

g = sns.displot(
    data=df,
    x="LOG_AMT_CREDIT",
    hue="NAME_CONTRACT_TYPE",
    bins=50,
    element="step",
    stat="density",
    col="TARGET",
    common_norm=False
)

for ax in g.axes.flat:
    ax.ticklabel_format(style='plain', axis='x')
    ax.ticklabel_format(style='plain', axis='y')

#default and the mont of the loan have negative correlation. In both type of contracts. That's a good proof about the similar behaivor between clases 
#and seems unnecesary split and train 2 diferent models.

In [ ]:
bins= np.arange(0,df["AMT_CREDIT"].max() + 100000, 100000)
df["BINED_AMT_CREDIT"]=  pd.qcut(df["AMT_CREDIT"],10)
df_groupBy_bins = df.groupby(["BINED_AMT_CREDIT","NAME_CONTRACT_TYPE"],observed=True)["TARGET"].agg(
    DEFAULT_RATE="mean",
    COUNT="size").reset_index()
df_groupBy_bins["CREDIT_BIN_CENTER"] = df_groupBy_bins["BINED_AMT_CREDIT"].apply(lambda x: x.mid)


gr=sns.relplot(data=df_groupBy_bins,x="CREDIT_BIN_CENTER",y="DEFAULT_RATE",kind="line",col="NAME_CONTRACT_TYPE")

In [ ]:
sns.scatterplot(
    data=df_groupBy_bins,
    x="CREDIT_BIN_CENTER",
    y="DEFAULT_RATE",
    hue="NAME_CONTRACT_TYPE",
    size="COUNT"
)

In [ ]:
"""About the idea of creating 2 different models for each type of contract: 

The amount of data and events is something to consider.
revolving loans represent 9.5% of observations and have a default ratio of 5%.
Therefore, train separate models significantly reduce the amount of total data and default events.

the analysis of the deciles of amount of credit and their respective default rate show similar overall trends for both contracts types, but have noticiable diferences in some segments.
For linear models this would require some features to model the interaction but in case of using tree based models the feature CONTRACT_TYPE 
seems enough

In conclusion, this preliminary analisis show there is no strong evidence supporting the need for two separate models. Even so, this hypothesis
will be tested formally later comparing model performance.
"""

In [ ]:
bureau_df=pd.read_csv("../data/bureau.csv")
bureau_df.head()

In [ ]:
create_files_nulls_per_colmun(bureau_df,"bureau")

In [ ]:
previous=pd.read_csv("../data/previous_application.csv")
previous.head()

In [ ]:
create_files_nulls_per_colmun(previous,"previous_aplication")