In [3]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import json
from scipy.stats import trim_mean
import math
from pandas.api.types import ( is_numeric_dtype, is_categorical_dtype, is_object_dtype, is_datetime64_any_dtype )
from default_risk.scripts.variable_profiling import eda_per_table_printing_results
from default_risk.scripts.variable_profiling import eda_per_table_persisting_result_html
from default_risk.scripts.variable_profiling import create_files_nulls_per_colmun
from default_risk.scripts.auxiliar_eda_function import recreate_and_sort_series_given_rows
from default_risk.scripts.auxiliar_eda_function import recreate_and_sort_the_serie_given_ids
from default_risk.scripts.auxiliar_eda_function import check_invariant

import default_risk.config as cfg
import dtale
import logging


installments_payment_df = pd.read_csv(cfg.INSTALLMENTS_PAYMENTS)

column_order_reference="DAYS_INSTALMENT"


data_frame_size=len(installments_payment_df)


installments_payment_df.sort_values(["SK_ID_PREV",column_order_reference,"DAYS_ENTRY_PAYMENT"],inplace=True)


log = logging.getLogger('werkzeug')


with open(cfg.SCHEMA_JSON, "r") as f:
    schema = json.load(f)

#aux function to avoid repeated code but keep idempotence between celds
def analyze_repeated_instalments(extra_mask,case_description) :
    next_installment_number = installments_payment_df.groupby("SK_ID_PREV")["NUM_INSTALMENT_NUMBER"].shift(-1)
    rows_to_analyze = installments_payment_df[
    (installments_payment_df ["NUM_INSTALMENT_NUMBER"] == next_installment_number) 
    &
    (extra_mask)]
    print("we have " + str(len(rows_to_analyze)) + " " + case_description + "\n")
    display(rows_to_analyze.head(50))
    return rows_to_analyze

def get_full_sorted_serie_rows(rows : pd.DataFrame):
   return recreate_and_sort_series_given_rows(rows,installments_payment_df, "SK_ID_PREV",column_order_reference)

def get_full_sorted_serie_ids(ids : list):
    recreate_and_sort_the_serie_given_ids(ids,installments_payment_df, "SK_ID_PREV" ,column_order_reference)

Invariants:

1- the column DAYS_INSTALMENT is left capped in -2922 (100%) #4

2- the values in column DAYS_ENTRY_PAYMENT < -2952 (99.99%) #4

Soft constraints: 

1- The series starts in NUM_INSTALMENT_NUMBER = 1 or with a date older than -2890 in DAYS_INSTALMENT. Meaning that or we have register from the first installment or the first part
of the loan are beyond the temporal umbral to register data in this table. We have in train 997752 ids of previous contracts (temporal series) and just 253 series don't accomplish this rule.
(99.98%) #5
anomalies: incomplete series. 


Decisions summary: 

1- We will divide the missing values  at AMT_PAYMENT -  DAYS_ENTRY_PAYMENT in 2 diferent cases at the moment of taking metrics.

    a- Dead tails: Where the values miss and stay as nan in the remaining rows of the serie and show now relevant change in other variable. This suggest administral padding 
    so we will ignore dead tails to the compute of agg metrics.

    b- Remaining cases: Are less than 50, even if are interesting we don't have enough observations to modelate it, so we will input it with foward

2- Catch incomplete series: There is series that's does not start in NUM_INSTALMENT_NUMBER = 1 and they oldest date is < -2890 

3- For every value in DAYS_ENTRY_PAYMENT that don't fullfill the invariant #2 we will cap the value in DAYS_INSTALMENT + 30. In that way, if in the future we want to capture metrics of days of payments, that values will not destroy the proportion.

In [4]:
#1
#files for the data dictionary
create_files_nulls_per_colmun(installments_payment_df,"installments_payment")

In [ ]:
#2
#runing screening script
eda_per_table_printing_results(installments_payment_df,schema,"installments_payments",False)

Warning: 'SK_ID_PREV' not found in schema for 'installments_payment'. Defaulting to categorical.
Warning: 'SK_ID_CURR' not found in schema for 'installments_payment'. Defaulting to categorical.
Warning: 'NUM_INSTALMENT_VERSION' not found in schema for 'installments_payment'. Defaulting to categorical.
Warning: 'NUM_INSTALMENT_NUMBER' not found in schema for 'installments_payment'. Defaulting to categorical.
Warning: 'DAYS_INSTALMENT' not found in schema for 'installments_payment'. Defaulting to categorical.
Warning: 'DAYS_ENTRY_PAYMENT' not found in schema for 'installments_payment'. Defaulting to categorical.
Warning: 'AMT_INSTALMENT' not found in schema for 'installments_payment'. Defaulting to categorical.
Warning: 'AMT_PAYMENT' not found in schema for 'installments_payment'. Defaulting to categorical.
--------------------------------------
SK_ID_PREV
basic_data

   cardinality       mode
0       997752  [2360056]

frequency

    CATEGORY  COUNT SEGMENT
0    2360056    293     top
1    2592574    279     top
2    1017477    248     top
3    1449382    243     top
4    1746731    236     top
5    1690678    223     top
6    2709164    222     top
7    1383111    220     top
8    1152155    219     top
9    2543266    216     top
10   2363104    215     top
11   1596156    214     top
12   2388698    213     top
13   2425232    213     top
14   1367696    211     top
15   1689292    211     top
16   2532655    209     top
17   1242387    209     top
18   2221414    209     top
19   1392344    207     top
20   1331992      1  bottom
21   1075611      1  bottom
22   2797899      1  bottom
23   2004857      1  bottom
24   2318385      1  bottom
25   2230170      1  bottom
26   1075615      1  bottom
27   1156672      1  bottom
28   1156667      1  bottom
29   1847907      1  bottom
30   1644186      1  bottom
31   1513970      1  bottom
32   2438133      1  bottom
33   1075625      1  bottom
34   1513972      1  bottom
35   1156622      1  bottom
36   1156597      1  bottom
37   1644163      1  bottom
38   1847936      1  bottom
39   1213890      1  bottom

--------------------------------------
SK_ID_CURR
basic_data

   cardinality      mode
0       339587  [145728]

frequency

    CATEGORY  COUNT SEGMENT
0     145728    372     top
1     296205    350     top
2     453103    347     top
3     189699    344     top
4     186851    337     top
5     172690    336     top
6     418081    332     top
7     192083    324     top
8     434807    323     top
9     217360    318     top
10    209362    318     top
11    179215    318     top
12    380048    317     top
13    111137    315     top
14    110917    314     top
15    422431    313     top
16    423106    313     top
17    388717    313     top
18    296364    312     top
19    382563    312     top
20    399396      1  bottom
21    155242      1  bottom
22    395383      1  bottom
23    282521      1  bottom
24    358247      1  bottom
25    303446      1  bottom
26    224555      1  bottom
27    293928      1  bottom
28    444767      1  bottom
29    100254      1  bottom
30    312842      1  bottom
31    111915      1  bottom
32    396690      1  bottom
33    303674      1  bottom
34    229819      1  bottom
35    156482      1  bottom
36    246347      1  bottom
37    399023      1  bottom
38    421618      1  bottom
39    211584      1  bottom

--------------------------------------
NUM_INSTALMENT_VERSION
basic_data

   cardinality   mode
0           65  [1.0]

frequency

    CATEGORY    COUNT SEGMENT
0        1.0  8485004    full
1        0.0  4082498    full
2        2.0   620283    full
3        3.0   237063    full
4        4.0    55274    full
..       ...      ...     ...
60      57.0        1    full
61      59.0        1    full
62     178.0        1    full
63      73.0        1    full
64      68.0        1    full

[65 rows x 3 columns]

--------------------------------------
NUM_INSTALMENT_NUMBER
basic_data

   cardinality mode
0          277  [1]

frequency

     CATEGORY    COUNT SEGMENT
0           1  1004160    full
1           2   985716    full
2           3   968279    full
3           4   943502    full
4           5   880007    full
..        ...      ...     ...
272       269        2    full
273       266        2    full
274       274        1    full
275       276        1    full
276       277        1    full

[277 rows x 3 columns]

--------------------------------------
DAYS_INSTALMENT
basic_data

   cardinality      mode
0         2922  [-120.0]

frequency

    CATEGORY  COUNT SEGMENT
0     -120.0  11512     top
1     -180.0  11212     top
2     -150.0  11194     top
3     -119.0  11183     top
4     -149.0  11144     top
5     -210.0  11140     top
6      -90.0  11135     top
7     -148.0  10922     top
8     -179.0  10838     top
9      -59.0  10828     top
10    -209.0  10821     top
11    -240.0  10819     top
12    -182.0  10804     top
13    -208.0  10764     top
14     -60.0  10754     top
15    -239.0  10695     top
16    -178.0  10683     top
17     -89.0  10681     top
18    -147.0  10648     top
19    -118.0  10629     top
20   -2870.0   1441  bottom
21   -2866.0   1438  bottom
22   -2921.0   1436  bottom
23   -2905.0   1436  bottom
24   -2894.0   1432  bottom
25   -2915.0   1422  bottom
26   -2901.0   1421  bottom
27   -2903.0   1415  bottom
28   -2892.0   1414  bottom
29   -2912.0   1413  bottom
30   -2906.0   1406  bottom
31   -2908.0   1403  bottom
32   -2904.0   1401  bottom
33   -2886.0   1401  bottom
34   -2902.0   1393  bottom
35   -2916.0   1391  bottom
36   -2899.0   1387  bottom
37   -2922.0   1327  bottom
38      -2.0    661  bottom
39      -1.0      2  bottom

--------------------------------------
DAYS_ENTRY_PAYMENT
basic_data

   cardinality     mode
0         3040  [-91.0]

frequency

    CATEGORY  COUNT SEGMENT
0      -91.0  13103     top
1     -182.0  13090     top
2     -154.0  13071     top
3      -92.0  12646     top
4     -245.0  12405     top
5     -273.0  12151     top
6     -119.0  11961     top
7      -63.0  11938     top
8     -153.0  11839     top
9     -336.0  11839     top
10    -120.0  11775     top
11    -210.0  11751     top
12    -183.0  11614     top
13    -126.0  11560     top
14    -122.0  11503     top
15    -217.0  11493     top
16    -184.0  11374     top
17    -123.0  11258     top
18    -308.0  11199     top
19    -181.0  11187     top
20   -3063.0      1  bottom
21   -3129.0      1  bottom
22   -3096.0      1  bottom
23   -3043.0      1  bottom
24   -3011.0      1  bottom
25   -3115.0      1  bottom
26   -3021.0      1  bottom
27   -3160.0      1  bottom
28   -3025.0      1  bottom
29   -3023.0      1  bottom
30   -3054.0      1  bottom
31   -3078.0      1  bottom
32   -3040.0      1  bottom
33   -4921.0      1  bottom
34   -3006.0      1  bottom
35   -3071.0      1  bottom
36   -3010.0      1  bottom
37   -3015.0      1  bottom
38   -3061.0      1  bottom
39   -3082.0      1  bottom

--------------------------------------
AMT_INSTALMENT
basic_data

   cardinality      mode
0       902539  [9000.0]

frequency

      CATEGORY   COUNT SEGMENT
0     9000.000  254062     top
1     2250.000  179120     top
2     4500.000  174143     top
3     6750.000  173659     top
4     3375.000  149941     top
5     5625.000   96362     top
6     7875.000   60248     top
7     1125.000   60224     top
8    13500.000   42926     top
9     8100.000   37295     top
10   10800.000   30054     top
11    4050.000   29264     top
12     225.000   28688     top
13     450.000   26207     top
14      67.500   25229     top
15     900.000   23504     top
16    5400.000   18647     top
17   11250.000   18238     top
18    1350.000   16668     top
19   22500.000   14701     top
20  266063.175       1  bottom
21   22240.485       1  bottom
22   48587.040       1  bottom
23   55226.610       1  bottom
24  222764.220       1  bottom
25   64478.655       1  bottom
26   75832.965       1  bottom
27  101424.375       1  bottom
28   34042.635       1  bottom
29  595365.030       1  bottom
30   27764.955       1  bottom
31  100925.010       1  bottom
32  877461.660       1  bottom
33  419578.200       1  bottom
34   81744.030       1  bottom
35   75741.885       1  bottom
36   24713.955       1  bottom
37   52813.305       1  bottom
38   41598.945       1  bottom
39  333361.485       1  bottom

--------------------------------------
AMT_PAYMENT
basic_data

   cardinality      mode
0       944236  [9000.0]

frequency

      CATEGORY   COUNT SEGMENT
0     9000.000  248757     top
1     2250.000  182654     top
2     4500.000  178309     top
3     6750.000  170360     top
4     3375.000  141832     top
5     5625.000   91165     top
6     1125.000   64440     top
7     7875.000   55823     top
8    13500.000   46276     top
9     8100.000   35271     top
10     225.000   30475     top
11     450.000   28530     top
12   10800.000   27975     top
13    4050.000   27640     top
14     900.000   25630     top
15   22500.000   23765     top
16      67.500   21246     top
17   11250.000   19686     top
18    5400.000   19550     top
19   45000.000   17449     top
20   38720.610       1  bottom
21   40811.265       1  bottom
22  541466.955       1  bottom
23  220108.050       1  bottom
24   58941.630       1  bottom
25   38410.380       1  bottom
26   22184.775       1  bottom
27   68567.400       1  bottom
28   28268.955       1  bottom
29   74983.455       1  bottom
30   47886.210       1  bottom
31  339221.565       1  bottom
32   89004.465       1  bottom
33   20917.755       1  bottom
34   25980.165       1  bottom
35  336259.485       1  bottom
36  206374.455       1  bottom
37   19532.250       1  bottom
38   22783.725       1  bottom
39  333361.485       1  bottom

In [6]:
#3
prev_id= installments_payment_df["SK_ID_PREV"].unique()
series_to_show= prev_id[:100]
dtale.show(get_full_sorted_serie_ids(series_to_show))

2026-05-10 19:11:20,588 - ERROR    - Exception on /health [GET]
Traceback (most recent call last):
  File "c:\Users\kuroc\OneDrive\Escritorio\default risk\default-risk\Lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\kuroc\OneDrive\Escritorio\default risk\default-risk\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\kuroc\OneDrive\Escritorio\default risk\default-risk\Lib\site-packages\flask\app.py", line 1821, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\kuroc\OneDrive\Escritorio\default risk\default-risk\Lib\site-packages\flask\app.py", line 2313, in preprocess_request
    rv = self.ensure_sync(before_func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\kuroc\OneDrive\Escritorio\default risk\default-risk\Lib\site-packages\dash\dash.py", line 1318, in _setup_server
    self._generate_scripts_html()
  File "c:\Users\kuroc\OneDrive\Escritorio\default risk\default-risk\Lib\site-packages\dash\dash.py", line 821, in _generate_scripts_html
    + self._collect_and_register_resources(
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\kuroc\OneDrive\Escritorio\default risk\default-risk\Lib\site-packages\dash\dash.py", line 764, in _collect_and_register_resources
    _relative_url_path(
  File "c:\Users\kuroc\OneDrive\Escritorio\default risk\default-risk\Lib\site-packages\dash\dash.py", line 743, in _relative_url_path
    modified = int(os.stat(module_path).st_mtime)
                   ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado: 'c:\\Users\\kuroc\\OneDrive\\Escritorio\\default risk\\default-risk\\Lib\\site-packages\\dash_daq\\async-slider.js'

In [7]:
#4
check_invariant(installments_payment_df["DAYS_INSTALMENT"] < -2922,"cases where have a older date than -2922 days", data_frame_size)

check_invariant(installments_payment_df["DAYS_ENTRY_PAYMENT"] < -2952,"cases where have a older date than -2922 days", data_frame_size)

0 of cases where cases where have a older date than -2922 days
that represent a 0.0% of cases with violation of this invariant

820 of cases where cases where have a older date than -2922 days
that represent a 0.006027018240770706% of cases with violation of this invariant

In [8]:
dtale.show(get_full_sorted_serie_rows(installments_payment_df[installments_payment_df["DAYS_ENTRY_PAYMENT"] < -3100]))

In [9]:
#5

grouped = installments_payment_df.groupby("SK_ID_PREV")

print(installments_payment_df["SK_ID_PREV"].nunique())

min_installment = grouped["NUM_INSTALMENT_NUMBER"].min()
min_days = grouped["DAYS_INSTALMENT"].min()

anomaly_condition = ( (min_installment > 1) & (min_days > -2890) )

anomaly_ids = anomaly_condition.index[anomaly_condition]

anomaly_rows = installments_payment_df[installments_payment_df["SK_ID_PREV"].isin(anomaly_ids)]

print(anomaly_rows["SK_ID_PREV"].nunique())

dtale.show(get_full_sorted_serie_rows(anomaly_rows))

997752
253

In [10]:
#in order to undestand the nature behind the missing values of DAYS_ENTRY_PAYMENT
rows_with_nulls=installments_payment_df[installments_payment_df["DAYS_ENTRY_PAYMENT"].isna()]
dtale.show(get_full_sorted_serie_rows(rows_with_nulls))

#in all the visualizated cases the tendence of the missing values is to show ups at the end of the secuence, like padding, so a "dead tail" definition is needed.
#Also, in the contract of SK_ID_PREV= 1004174 we can observe a jump from 8 to 101 in "NUM_INSTALMENT_NUMBER".
#This suggest that could exist errors in the counter or a sentinel / special value (101 show ups in more rows).

In [11]:
#now, let's validate the hipotesis of missing values in DAYS_ENTRY_PAYMENT y AMT_PAYMENT are dead tails. For that we will analize if exists cases
#that once the serie have a missing value in these columns, can exist a row with a value different a nan, of if once hit nan, it's always nan without relevant changes.
installments_payment_df["NEXT_VALUE_PAYMENT"] = installments_payment_df.groupby("SK_ID_PREV")["DAYS_ENTRY_PAYMENT"].shift(-1)
not_a_deadtail_mask= (installments_payment_df["DAYS_ENTRY_PAYMENT"].isna() ) & ( installments_payment_df["NEXT_VALUE_PAYMENT"].notna())
print(not_a_deadtail_mask.sum())
potencial_incosistencies_rows= installments_payment_df[not_a_deadtail_mask]
dtale.show(get_full_sorted_serie_rows(potencial_incosistencies_rows))
#When we exclude dead tail cases the remaining observation of missing values in DAYS_ENTRY_PAYMENT are less than 50. 
#Also these series exhib an anormal behaivor. Seems like have another schedule with their own counter, using the prefix "100" (101,102,103...) in NUM_INSTALLMENT_NUMBER and a different NUM_INSTALLMEMT_VERSION.

44

In [12]:
#now let's analize the behaivor of the rows when the installment number jump to 100.
groups_sizes= installments_payment_df.groupby("SK_ID_PREV")["SK_ID_PREV"].transform("size")
series_bellow_hundred_rows= installments_payment_df[groups_sizes < 100]
rows_with_notation= series_bellow_hundred_rows[series_bellow_hundred_rows["NUM_INSTALMENT_NUMBER"] > 100]
dtale.show(get_full_sorted_serie_rows(rows_with_notation)) 
#This installments with diferent numeration (100 prefix) and also have a diferent (NUM_INSTALMENT_VERSION) appears to have a high correlation with repeated "NUM_INSTALMENT_NUMBER"
#and how this usually this represent a underpayment in that month we come with the hipotesis of, this specials insatllments could be extra fees for that.

In [13]:

grouped_per_contracts= installments_payment_df.groupby("SK_ID_PREV")
contracts_with_no_repeated_installments= grouped_per_contracts["NUM_INSTALMENT_NUMBER"].nunique() == grouped_per_contracts["NUM_INSTALMENT_NUMBER"].size()
ids_contracts_to_analize= contracts_with_no_repeated_installments.index[contracts_with_no_repeated_installments]
series_with_repetead_installments= installments_payment_df[installments_payment_df["SK_ID_PREV"].isin(ids_contracts_to_analize)]
groups_sizes= series_with_repetead_installments.groupby("SK_ID_PREV").transform("size")
series_bellow_hundred_rows= series_with_repetead_installments[(groups_sizes < 80)]
rows_with_notation= series_bellow_hundred_rows[series_bellow_hundred_rows["NUM_INSTALMENT_NUMBER"] > 100]
print(len(rows_with_notation))
dtale.show(get_full_sorted_serie_rows(rows_with_notation))

1002

In [14]:


rows= installments_payment_df[(installments_payment_df["DAYS_INSTALMENT"] > installments_payment_df["DAYS_ENTRY_PAYMENT"])]
dtale.show(get_full_sorted_serie_rows(rows))

In [15]:
grouped_per_contracts= installments_payment_df.groupby("SK_ID_PREV")
contracts_with_no_repeated_installments= grouped_per_contracts["NUM_INSTALMENT_NUMBER"].nunique() == grouped_per_contracts["NUM_INSTALMENT_NUMBER"].size()
ids_contracts_to_analize= contracts_with_no_repeated_installments.index[~contracts_with_no_repeated_installments]
series_with_repetead_installments= installments_payment_df[installments_payment_df["SK_ID_PREV"].isin(ids_contracts_to_analize)]
dtale.show(series_with_repetead_installments)

In [18]:
#now, before end the EDA of this table we want to understand the nature behind of the repeated number of installments
rows_that_repeat_number= analyze_repeated_instalments(True,"of cases where the installment number are repeated")
dtale.show(get_full_sorted_serie_rows(rows_that_repeat_number))
#this show how repeated installments mainly represent underpayment / partial payment of a installment. So, let's check if could be generated for other reason.

we have 741703 of cases where the installment number are repeated

,SK_ID_PREV,SK_ID_CURR,NUM_INSTALMENT_VERSION,NUM_INSTALMENT_NUMBER,DAYS_INSTALMENT,DAYS_ENTRY_PAYMENT,AMT_INSTALMENT,AMT_PAYMENT,NEXT_VALUE_PAYMENT
2618814,1000005,176456,1.0,9,-1448.0,-1484.0,14713.605,2.790,-1445.0
10749262,1000015,315553,1.0,5,-1243.0,-1278.0,5597.460,2.160,-1239.0
251801,1000019,176905,1.0,7,-2127.0,-2157.0,6072.165,0.090,-2125.0
13477241,1000041,449214,1.0,5,-2813.0,-2857.0,2357.910,133.875,-2811.0
11802025,1000041,449214,1.0,9,-2693.0,-2796.0,2357.910,147.735,-2685.0
12929880,1000041,449214,1.0,10,-2663.0,-2685.0,2357.910,147.825,-2657.0
916729,1000049,176852,1.0,1,-315.0,-326.0,4834.395,18000.000,-326.0
2408005,1000049,176852,4.0,2,-285.0,-297.0,14592.690,18000.000,-297.0
4250206,1000051,234782,1.0,8,-1511.0,-1516.0,3550.095,3546.000,-1491.0
4706039,1000051,234782,1.0,9,-1481.0,-1491.0,3550.095,3546.000,-1455.0
6672947,1000051,234782,1.0,10,-1451.0,-1455.0,3550.095,3546.000,-1432.0
5973197,1000051,234782,1.0,11,-1421.0,-1432.0,3550.095,3546.000,-1406.0
2409298,1000052,189926,1.0,6,-937.0,-964.0,15065.235,450.765,-933.0
388957,1000052,189926,1.0,7,-907.0,-933.0,15065.235,450.765,-904.0
2421826,1000052,189926,1.0,9,-847.0,-876.0,15065.235,450.765,-838.0
1500521,1000052,189926,1.0,10,-817.0,-838.0,14928.570,450.765,-810.0
9413379,1000053,399400,1.0,4,-1305.0,-1339.0,5706.675,2924.595,-1303.0
7436029,1000055,238221,1.0,5,-1043.0,-1059.0,3839.400,3243.105,-1009.0
4502009,1000055,238221,1.0,5,-1043.0,-1009.0,3839.400,465.795,-995.0
4130329,1000055,238221,1.0,6,-1013.0,-1009.0,3839.400,2422.755,-995.0
7063256,1000062,206673,1.0,1,-2324.0,-2332.0,6079.140,2038.590,-2313.0
12625204,1000065,409776,1.0,14,-19.0,-50.0,4716.990,182.250,-14.0
10984708,1000074,392725,1.0,1,-207.0,-215.0,2808.270,2706.930,-187.0
7992037,1000076,353253,1.0,6,-358.0,-361.0,14534.775,91.125,-351.0
8114142,1000076,353253,1.0,7,-328.0,-331.0,14534.775,92.475,-320.0
8754519,1000076,353253,1.0,8,-298.0,-320.0,14534.775,93.825,-288.0
8467875,1000076,353253,1.0,10,-238.0,-237.0,14534.775,4146.525,-232.0
8445581,1000076,353253,1.0,11,-208.0,-212.0,14534.775,4012.875,-201.0
8610355,1000076,353253,1.0,12,-178.0,-177.0,14517.315,281.790,-175.0
12905981,1000078,404074,1.0,7,-915.0,-948.0,9386.910,471.465,-911.0
13056082,1000078,404074,1.0,9,-855.0,-884.0,9386.910,597.645,-850.0
10118750,1000079,351559,1.0,3,-1382.0,-1417.0,4237.290,39.420,-1380.0
7797167,1000079,351559,1.0,8,-1232.0,-1284.0,4237.020,677.970,-1221.0
12544702,1000080,450808,1.0,7,-1288.0,-1324.0,6113.970,7.650,-1277.0
12556355,1000081,417435,2.0,2,-359.0,-378.0,202978.530,225000.000,-378.0
9045155,1000082,330786,1.0,16,-227.0,-256.0,59074.335,2955.330,-221.0
9465026,1000087,399664,0.0,1,-913.0,-927.0,5449.365,5175.000,-916.0
5920411,1000090,256713,1.0,3,-840.0,-873.0,52953.705,298.440,-838.0
7492708,1000090,256713,1.0,9,-660.0,-691.0,52953.705,5226.210,-658.0
5959750,1000090,256713,1.0,18,-390.0,-424.0,52953.705,13742.865,-387.0
5072938,1000090,256713,1.0,28,-90.0,-90.0,52953.705,46255.815,-88.0
9715528,1000092,371738,1.0,8,-2512.0,-2544.0,4332.375,4.905,-2509.0
8611176,1000092,371738,1.0,9,-2482.0,-2509.0,4332.375,4.905,-2479.0
10633723,1000094,359175,0.0,2,-2597.0,-2603.0,9000.000,4500.000,-2580.0
8944693,1000096,306118,0.0,47,-1872.0,-1902.0,1220.895,117.855,-1883.0
10409861,1000096,306118,0.0,49,-1844.0,-1871.0,67.500,21.960,-1841.0
8717274,1000096,306118,0.0,50,-1813.0,-1841.0,67.500,21.960,-1755.0
9556800,1000096,306118,0.0,52,-1752.0,-1755.0,67.500,3.960,-1730.0
3891640,1000100,243621,1.0,10,-752.0,-781.0,10778.670,10568.880,-746.0
208406,1000104,145138,1.0,4,-2854.0,-2828.0,3593.655,3588.525,-2814.0

In [17]:
"""In order to show the cases where the instalment number tends to repeat, we create the cases of analysis 1,2,3,4 with their explanations above their respective code.
the conclusions are these: The instalment tends to repeat in events of underpayment / partial payment, for change in the version of the schedule, so the number can repeat even with 
full payment of the instalment if the schedule changes (NUM_INSTALMENT_VERSION). Beyond these dominant patterns we also found one more case where the instalment number 
can repeat and is highly correlated with what appears to be advance payment behavior. If you try to look for cases where "AMT_PAYMENT" == "AMT_INSTALMENT" and the schedule
don't change (NUM_INSTALMENT_VERSION) you will discover that there are no cases that meet these conditions at the same time (3rd analysis). But if you add that the payment can be 0 
("AMT_PAYMENT" == 0) it becomes possible to observe cases of full payment without reschedule. (4th analysis)"""

installments_payment_df["NEXT_INSTALLMENT_VERSION"] = installments_payment_df.groupby("SK_ID_PREV")["NUM_INSTALMENT_VERSION"].shift(-1)
same_version_versions_mask= (installments_payment_df ["NUM_INSTALMENT_VERSION"]==installments_payment_df["NEXT_INSTALLMENT_VERSION"])
full_installment_payment_mask= (installments_payment_df ["AMT_INSTALMENT"] == installments_payment_df["AMT_PAYMENT"])



#1- when the instalment number repeat but the installment was totaly paid
rows_repeated_installment_with_no_underpayment= analyze_repeated_instalments(full_installment_payment_mask, "of cases that repeat number of installment but it's not underpayment")

#2 - when the instalment number repeat and also the version
rows_same_version_and_installment_number= analyze_repeated_instalments(same_version_versions_mask,"of cases that repeat number of installment and version of the next row")

#3 - when the instalment number repeat, but it's not underpayment and the instalment version don't change (0 rows found, this does not happen in the dataset)
same_version_and_full_payment_mask = (same_version_versions_mask) & (full_installment_payment_mask)
rows_same_version_and_full_payment= analyze_repeated_instalments(same_version_and_full_payment_mask,"of cases that repeat number of installment and version of the next row")


#4 - the same that before but we allows to "AMT_INSTALMENT" being == 0. We want to include this because in previous analysis we discover that sometimes the number is repeated because 
#the installment was payment in advance and take another register repeating the instalment but with AMT_INSTALMENT being 0. (already paid)
full_payment_with_extra_row= (full_installment_payment_mask | (installments_payment_df["AMT_PAYMENT"] == 0))
same_version_and_full_payment_with_extra_row_mask = (same_version_versions_mask) & (full_payment_with_extra_row)
payed_in_advance_row= analyze_repeated_instalments(same_version_and_full_payment_with_extra_row_mask,"of cases that repeat instalment number for payment in advance")



installments_payment_df.drop(
    columns=["NEXT_INSTALLMENT_VERSION"],
    inplace=True
)

we have 372 of cases that repeat number of installment but it's not underpayment

,SK_ID_PREV,SK_ID_CURR,NUM_INSTALMENT_VERSION,NUM_INSTALMENT_NUMBER,DAYS_INSTALMENT,DAYS_ENTRY_PAYMENT,AMT_INSTALMENT,AMT_PAYMENT,NEXT_VALUE_PAYMENT,NEXT_INSTALLMENT_VERSION
7065125,1001784,233119,2.0,1,-153.0,-153.0,9000.000,9000.000,-150.0,3.0
7614568,1003455,205313,2.0,1,-104.0,-104.0,40500.000,40500.000,-102.0,4.0
4071653,1004144,211055,2.0,1,-107.0,-107.0,45000.000,45000.000,-99.0,5.0
7098611,1004144,211055,5.0,1,-99.0,-99.0,11250.405,11250.405,-92.0,6.0
6137646,1007577,264913,2.0,1,-120.0,-120.0,45000.000,45000.000,-102.0,3.0
3248061,1026181,178998,2.0,1,-157.0,-157.0,18000.000,18000.000,-157.0,3.0
497426,1034283,154042,2.0,1,-48.0,-48.0,9000.000,9000.000,-39.0,3.0
3082798,1036226,181948,1.0,13,-962.0,-971.0,7489.215,7489.215,-971.0,2.0
10202369,1049831,301360,2.0,1,-266.0,-266.0,31050.000,31050.000,-240.0,3.0
1620357,1051240,147426,2.0,1,-41.0,-41.0,22500.000,22500.000,-29.0,3.0
7218077,1051532,280177,2.0,1,-190.0,-190.0,180000.000,180000.000,-177.0,4.0
6508713,1051550,293563,2.0,1,-193.0,-194.0,8775.000,8775.000,-194.0,3.0
7823851,1057937,324839,2.0,1,-95.0,-95.0,13500.000,13500.000,-95.0,3.0
2145395,1058537,187790,10.0,4,-452.0,-454.0,7315.830,7315.830,-454.0,11.0
976605,1058537,187790,12.0,6,-392.0,-403.0,7227.000,7227.000,-403.0,13.0
12095204,1061547,441388,2.0,1,-212.0,-212.0,17775.000,17775.000,-212.0,3.0
2890628,1071570,157784,2.0,1,-105.0,-105.0,67500.000,67500.000,-83.0,3.0
1595122,1074494,103486,2.0,1,-63.0,-63.0,45000.000,45000.000,-36.0,3.0
12170365,1080682,440518,2.0,1,-206.0,-207.0,62100.000,62100.000,-203.0,3.0
10675146,1085784,352053,2.0,1,-90.0,-90.0,11025.000,11025.000,-65.0,3.0
11946932,1087181,452983,2.0,1,-37.0,-37.0,22500.000,22500.000,-15.0,4.0
12414442,1087181,452983,4.0,1,-15.0,-15.0,10795.500,10795.500,-8.0,5.0
8678581,1091891,381381,2.0,1,-225.0,-225.0,13500.000,13500.000,-210.0,3.0
3912791,1092220,218431,2.0,1,-78.0,-81.0,51417.450,51417.450,-81.0,3.0
4849087,1092418,250082,2.0,1,-184.0,-184.0,6750.000,6750.000,-166.0,3.0
2517808,1096061,102206,2.0,1,-168.0,-175.0,12600.000,12600.000,-170.0,3.0
8640594,1097911,326606,2.0,1,-255.0,-255.0,31500.000,31500.000,-230.0,3.0
929347,1100930,188884,2.0,1,-107.0,-107.0,36000.000,36000.000,-86.0,3.0
9848671,1102848,353386,2.0,1,-56.0,-56.0,49500.000,49500.000,-56.0,3.0
12696631,1110271,442388,2.0,1,-116.0,-117.0,49500.000,49500.000,-117.0,3.0
12574463,1118694,404882,2.0,1,-31.0,-31.0,14400.000,14400.000,-31.0,3.0
8394335,1122469,323860,2.0,1,-186.0,-188.0,128142.000,128142.000,-188.0,3.0
2896653,1125863,108885,2.0,1,-136.0,-136.0,13500.000,13500.000,-123.0,4.0
8805270,1126006,340207,2.0,1,-40.0,-40.0,18000.000,18000.000,-32.0,3.0
2795074,1133646,101378,2.0,1,-132.0,-132.0,31500.000,31500.000,-125.0,3.0
8859051,1136081,305108,2.0,1,-265.0,-265.0,18000.000,18000.000,-248.0,3.0
13359030,1139774,410476,2.0,1,-208.0,-208.0,51750.000,51750.000,-196.0,3.0
12356918,1150254,426837,2.0,1,-41.0,-41.0,9000.000,9000.000,-41.0,3.0
5544189,1153115,233436,2.0,1,-74.0,-75.0,36000.000,36000.000,-62.0,3.0
1632223,1153497,122878,2.0,1,-17.0,-17.0,18000.000,18000.000,-6.0,3.0
13365470,1159357,401590,1.0,7,-1023.0,-1089.0,4429.170,4429.170,-1026.0,2.0
684036,1175528,102731,2.0,1,-208.0,-208.0,45000.000,45000.000,-193.0,3.0
6150029,1182537,205245,1.0,5,-620.0,-622.0,10212.975,10212.975,-622.0,2.0
13478515,1183972,415638,2.0,1,-29.0,-29.0,126000.000,126000.000,-29.0,3.0
1458373,1185983,140974,2.0,1,-48.0,-48.0,22500.000,22500.000,-48.0,3.0
7126523,1188788,206721,2.0,1,-66.0,-77.0,18000.000,18000.000,-60.0,3.0
6899013,1190641,239280,2.0,1,-147.0,-147.0,11700.000,11700.000,-135.0,5.0
8510502,1193597,366350,2.0,1,-29.0,-29.0,22500.000,22500.000,-24.0,3.0
10782834,1198656,346794,2.0,1,-31.0,-33.0,12600.000,12600.000,-33.0,3.0
8328951,1202619,323070,2.0,1,-105.0,-105.0,8100.000,8100.000,-105.0,3.0

we have 651557 of cases that repeat number of installment and version of the next row

,SK_ID_PREV,SK_ID_CURR,NUM_INSTALMENT_VERSION,NUM_INSTALMENT_NUMBER,DAYS_INSTALMENT,DAYS_ENTRY_PAYMENT,AMT_INSTALMENT,AMT_PAYMENT,NEXT_VALUE_PAYMENT,NEXT_INSTALLMENT_VERSION
2618814,1000005,176456,1.0,9,-1448.0,-1484.0,14713.605,2.790,-1445.0,1.0
10749262,1000015,315553,1.0,5,-1243.0,-1278.0,5597.460,2.160,-1239.0,1.0
251801,1000019,176905,1.0,7,-2127.0,-2157.0,6072.165,0.090,-2125.0,1.0
13477241,1000041,449214,1.0,5,-2813.0,-2857.0,2357.910,133.875,-2811.0,1.0
11802025,1000041,449214,1.0,9,-2693.0,-2796.0,2357.910,147.735,-2685.0,1.0
12929880,1000041,449214,1.0,10,-2663.0,-2685.0,2357.910,147.825,-2657.0,1.0
4250206,1000051,234782,1.0,8,-1511.0,-1516.0,3550.095,3546.000,-1491.0,1.0
4706039,1000051,234782,1.0,9,-1481.0,-1491.0,3550.095,3546.000,-1455.0,1.0
6672947,1000051,234782,1.0,10,-1451.0,-1455.0,3550.095,3546.000,-1432.0,1.0
5973197,1000051,234782,1.0,11,-1421.0,-1432.0,3550.095,3546.000,-1406.0,1.0
2409298,1000052,189926,1.0,6,-937.0,-964.0,15065.235,450.765,-933.0,1.0
388957,1000052,189926,1.0,7,-907.0,-933.0,15065.235,450.765,-904.0,1.0
2421826,1000052,189926,1.0,9,-847.0,-876.0,15065.235,450.765,-838.0,1.0
1500521,1000052,189926,1.0,10,-817.0,-838.0,14928.570,450.765,-810.0,1.0
9413379,1000053,399400,1.0,4,-1305.0,-1339.0,5706.675,2924.595,-1303.0,1.0
7436029,1000055,238221,1.0,5,-1043.0,-1059.0,3839.400,3243.105,-1009.0,1.0
4502009,1000055,238221,1.0,5,-1043.0,-1009.0,3839.400,465.795,-995.0,1.0
4130329,1000055,238221,1.0,6,-1013.0,-1009.0,3839.400,2422.755,-995.0,1.0
7063256,1000062,206673,1.0,1,-2324.0,-2332.0,6079.140,2038.590,-2313.0,1.0
12625204,1000065,409776,1.0,14,-19.0,-50.0,4716.990,182.250,-14.0,1.0
10984708,1000074,392725,1.0,1,-207.0,-215.0,2808.270,2706.930,-187.0,1.0
7992037,1000076,353253,1.0,6,-358.0,-361.0,14534.775,91.125,-351.0,1.0
8114142,1000076,353253,1.0,7,-328.0,-331.0,14534.775,92.475,-320.0,1.0
8754519,1000076,353253,1.0,8,-298.0,-320.0,14534.775,93.825,-288.0,1.0
8467875,1000076,353253,1.0,10,-238.0,-237.0,14534.775,4146.525,-232.0,1.0
8445581,1000076,353253,1.0,11,-208.0,-212.0,14534.775,4012.875,-201.0,1.0
8610355,1000076,353253,1.0,12,-178.0,-177.0,14517.315,281.790,-175.0,1.0
12905981,1000078,404074,1.0,7,-915.0,-948.0,9386.910,471.465,-911.0,1.0
13056082,1000078,404074,1.0,9,-855.0,-884.0,9386.910,597.645,-850.0,1.0
10118750,1000079,351559,1.0,3,-1382.0,-1417.0,4237.290,39.420,-1380.0,1.0
7797167,1000079,351559,1.0,8,-1232.0,-1284.0,4237.020,677.970,-1221.0,1.0
12544702,1000080,450808,1.0,7,-1288.0,-1324.0,6113.970,7.650,-1277.0,1.0
9045155,1000082,330786,1.0,16,-227.0,-256.0,59074.335,2955.330,-221.0,1.0
9465026,1000087,399664,0.0,1,-913.0,-927.0,5449.365,5175.000,-916.0,0.0
5920411,1000090,256713,1.0,3,-840.0,-873.0,52953.705,298.440,-838.0,1.0
7492708,1000090,256713,1.0,9,-660.0,-691.0,52953.705,5226.210,-658.0,1.0
5959750,1000090,256713,1.0,18,-390.0,-424.0,52953.705,13742.865,-387.0,1.0
5072938,1000090,256713,1.0,28,-90.0,-90.0,52953.705,46255.815,-88.0,1.0
9715528,1000092,371738,1.0,8,-2512.0,-2544.0,4332.375,4.905,-2509.0,1.0
8611176,1000092,371738,1.0,9,-2482.0,-2509.0,4332.375,4.905,-2479.0,1.0
10633723,1000094,359175,0.0,2,-2597.0,-2603.0,9000.000,4500.000,-2580.0,0.0
8944693,1000096,306118,0.0,47,-1872.0,-1902.0,1220.895,117.855,-1883.0,0.0
10409861,1000096,306118,0.0,49,-1844.0,-1871.0,67.500,21.960,-1841.0,0.0
8717274,1000096,306118,0.0,50,-1813.0,-1841.0,67.500,21.960,-1755.0,0.0
9556800,1000096,306118,0.0,52,-1752.0,-1755.0,67.500,3.960,-1730.0,0.0
3891640,1000100,243621,1.0,10,-752.0,-781.0,10778.670,10568.880,-746.0,1.0
208406,1000104,145138,1.0,4,-2854.0,-2828.0,3593.655,3588.525,-2814.0,1.0
1486172,1000104,145138,1.0,5,-2824.0,-2814.0,3593.655,3588.525,-2801.0,1.0
12358266,1000111,433531,1.0,1,-2030.0,-2039.0,34766.550,34762.500,-2007.0,1.0
12146211,1000111,433531,1.0,2,-2000.0,-2007.0,34766.550,34762.500,-1977.0,1.0

we have 0 of cases that repeat number of installment and version of the next row

Empty DataFrame
Columns: [SK_ID_PREV, SK_ID_CURR, NUM_INSTALMENT_VERSION, NUM_INSTALMENT_NUMBER, DAYS_INSTALMENT, DAYS_ENTRY_PAYMENT, AMT_INSTALMENT, AMT_PAYMENT, NEXT_VALUE_PAYMENT, NEXT_INSTALLMENT_VERSION]
Index: []

we have 1427 of cases that repeat instalment number for payment in advance

,SK_ID_PREV,SK_ID_CURR,NUM_INSTALMENT_VERSION,NUM_INSTALMENT_NUMBER,DAYS_INSTALMENT,DAYS_ENTRY_PAYMENT,AMT_INSTALMENT,AMT_PAYMENT,NEXT_VALUE_PAYMENT,NEXT_INSTALLMENT_VERSION
2841065,1000841,198725,0.0,29,-2271.0,-2298.0,9000.0,0.0,-2264.0,0.0
9485830,1000847,389124,0.0,3,-2301.0,-2330.0,9000.0,0.0,-2313.0,0.0
10518715,1000857,373592,0.0,4,-2445.0,-2471.0,6750.0,0.0,-2451.0,0.0
1358404,1001758,122569,0.0,8,-2402.0,-2432.0,1890.0,0.0,-2403.0,0.0
6373367,1004270,202138,0.0,28,-2279.0,-2307.0,6750.0,0.0,-2294.0,0.0
83015,1007055,155925,0.0,5,-2328.0,-2310.0,3375.0,0.0,-2291.0,0.0
3166130,1007055,155925,0.0,6,-2297.0,-2310.0,3375.0,0.0,-2291.0,0.0
2264269,1007055,155925,0.0,7,-2266.0,-2291.0,3375.0,0.0,-2261.0,0.0
235606,1007055,155925,0.0,8,-2236.0,-2261.0,3375.0,0.0,-2241.0,0.0
6704782,1007303,209013,0.0,20,-2215.0,-2245.0,3375.0,0.0,-2226.0,0.0
1667657,1007347,174190,0.0,23,-2357.0,-2385.0,6750.0,0.0,-2360.0,0.0
4410642,1007366,202872,0.0,18,-2275.0,-2288.0,5625.0,0.0,-2282.0,0.0
6577412,1007720,248320,0.0,7,-2295.0,-2312.0,3150.0,0.0,-2283.0,0.0
5900312,1007720,248320,0.0,8,-2264.0,-2283.0,3150.0,0.0,-2270.0,0.0
710456,1008956,116687,0.0,11,-2323.0,-2353.0,9000.0,0.0,-2336.0,0.0
10838644,1009844,334315,0.0,29,-2518.0,-2547.0,6750.0,0.0,-2528.0,0.0
3784916,1010429,179402,0.0,10,-2164.0,-2191.0,7875.0,0.0,-2169.0,0.0
7344430,1010600,270935,0.0,10,-2497.0,-2525.0,4500.0,0.0,-2497.0,0.0
7373376,1010600,270935,0.0,12,-2436.0,-2462.0,4500.0,0.0,-2447.0,0.0
5390655,1017222,250437,0.0,35,-2273.0,-2300.0,3375.0,0.0,-2272.0,0.0
5845770,1017222,250437,0.0,36,-2243.0,-2272.0,3375.0,0.0,-2262.0,0.0
839932,1017421,100198,0.0,11,-2213.0,-2226.0,3780.0,0.0,-2225.0,0.0
4212834,1020869,249882,0.0,9,-2433.0,-2450.0,9000.0,0.0,-2433.0,0.0
2395182,1024575,118244,0.0,36,-2268.0,-2293.0,7875.0,0.0,-2279.0,0.0
10095736,1025205,353666,0.0,41,-2245.0,-2261.0,4050.0,0.0,-2247.0,0.0
9644514,1026344,335059,0.0,20,-2259.0,-2289.0,9000.0,0.0,-2231.0,0.0
7420856,1026676,272292,0.0,17,-2382.0,-2409.0,6750.0,0.0,-2388.0,0.0
6262449,1027002,221059,0.0,12,-2439.0,-2465.0,6750.0,0.0,-2435.0,0.0
3942887,1027002,221059,0.0,13,-2409.0,-2435.0,6750.0,0.0,-2420.0,0.0
11058766,1029581,399336,0.0,23,-2221.0,-2240.0,6750.0,0.0,-2228.0,0.0
10645191,1029587,348709,0.0,20,-2444.0,-2473.0,5625.0,0.0,-2454.0,0.0
12768199,1029589,443609,0.0,4,-2178.0,-2193.0,9000.0,0.0,-2161.0,0.0
13092317,1029589,443609,0.0,5,-2148.0,-2161.0,9000.0,0.0,-2156.0,0.0
9055109,1035998,387473,0.0,10,-2408.0,-2438.0,6750.0,0.0,-2411.0,0.0
12603054,1036239,439553,0.0,19,-2194.0,-2222.0,9000.0,0.0,-2204.0,0.0
3423940,1041901,160093,0.0,23,-2362.0,-2391.0,9000.0,0.0,-2363.0,0.0
6463234,1049819,234679,0.0,21,-2240.0,-2268.0,9000.0,0.0,-2244.0,0.0
13022954,1050260,403863,0.0,21,-2353.0,-2381.0,7875.0,0.0,-2359.0,0.0
1692940,1052109,165681,0.0,24,-2295.0,-2296.0,9000.0,0.0,-2295.0,0.0
1635246,1052109,165681,0.0,25,-2264.0,-2275.0,9000.0,0.0,-2267.0,0.0
7803878,1052656,325988,0.0,26,-2447.0,-2477.0,4500.0,0.0,-2449.0,0.0
12408237,1052886,407401,0.0,23,-2274.0,-2294.0,3375.0,0.0,-2281.0,0.0
5311629,1054673,268418,0.0,4,-2390.0,-2415.0,9000.0,0.0,-2401.0,0.0
7897712,1054722,376797,0.0,15,-2368.0,-2372.0,5625.0,0.0,-2351.0,0.0
9730744,1054722,376797,0.0,16,-2337.0,-2351.0,5625.0,0.0,-2316.0,0.0
8641381,1054722,376797,0.0,17,-2306.0,-2316.0,5625.0,0.0,-2281.0,0.0
7999845,1060303,309856,0.0,21,-2241.0,-2267.0,13500.0,0.0,-2242.0,0.0
2106596,1061295,167947,0.0,8,-2512.0,-2541.0,6750.0,0.0,-2522.0,0.0
2358515,1061324,180237,0.0,14,-2303.0,-2330.0,5625.0,0.0,-2299.0,0.0
999751,1061324,180237,0.0,15,-2272.0,-2299.0,5625.0,0.0,-2271.0,0.0